---
- hosts: '{{target}}'
  vars_files:
    - "group_vars/main.yml"

  pre_tasks:
    - pause:
        prompt: |
          Which service do you want to restart?
          1- MSSQLSERVER
          2- SQLSERVERAGENT
      when: service is not defined
      register: prompt

    - name: Selected {{prompt.user_input}} for prompt
      set_fact:
        service: MSSQLSERVER
      when: service is not defined and prompt.user_input == "1"

  tasks:
    - name: Restarting {{service}} Service
      win_service:
        name: "{{service}}"
        state: restarted
      when: service is defined
