---
- hosts: web-servers
  remote_user: deploy
  tasks:
    - name: Restart rails (Passenger) web application
      command: /bin/bash -l -c  'touch /home/deploy/vertilux-accpac/current/tmp/restart.txt'