- hosts: localhost
  tasks:
    - name: Gather info about vCenter Extensions
      vcenter_extension_info:
        hostname: 172.16.1.92
        username: {{  }}
        password: {{  }}
        validate_certs: False
      register: ext_info
      delegate_to: localhost
