- hosts: data
  vars_files:
    - "vars/public.yml"
  remote_user: "{{remote_user}}"
  roles:
    - app-update
    - run-migrations
    - restart-sidekiq

- hosts: lb01,lb02,lb03,lb04
  vars_files:
    - "vars/public.yml"
  remote_user: "{{remote_user}}"
  roles:
    - app-update
    - restart-nginx
    - restart-sidekiq
