---
- hosts: web_servers
  remote_user: deploy

  pre_tasks:
    - pause:
        prompt: |
          Select environment:
          1- accltd
          2- bzidat
          3- covdat
          4- espdat
          5- mxpdat
          6- prndat
          7- pwcdat
          8- rdmdat
          9- saldat
          10- wcpdat
      when: env is not defined
      register: prompt

    - name: Set/Unset maintenance mode
      set_fact:
        env: accltd
      when: env is not defined

  tasks:
  - stat:
      path: /home/deploy/erp-{{env}}/current/tmp/maintenance.yml
    register: result
    when: env is defined

  - block:
    - debug:
        msg: "ERP maintenance mode is OFF"
    - name: Setting web servers to maintenance mode to ON
      command: /bin/bash -l -c 'cd /home/deploy/erp-{{env}}/current && bundle exec rake RAILS_ENV={{env}} maintenance:start'
      environment:
        PATH: "/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/bin:/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/shims:/home/deploy/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/sbin:/bin:/usr/games"
    when: result.stat.exists == false

  - block:
    - debug:
        msg: "ERP maintenance mode is ON"
    - name: Setting web servers to maintenance mode to OFF
      command: /bin/bash -l -c 'cd /home/deploy/erp-{{env}}/current && bundle exec rake RAILS_ENV={{env}} maintenance:end'
      environment:
        PATH: "/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/bin:/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/shims:/home/deploy/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/sbin:/bin:/usr/games"
    when: result.stat.exists == true
