---
- hosts: web_servers
  remote_user: deploy

  vars_prompt:
    - name: env
      prompt: "Please enter environment"
      private: no
    - name: version
      prompt: "Please enter version"
      private: no

  tasks:
    - name: Rename erp-{{env}} to erp-{{env}}-{{version}}
      command: mv /home/deploy/erp-{{env}} /home/deploy/erp-{{env}}-{{version}}

    - name: Get all original config files
      find:
        paths: "/home/deploy/erp-{{env}}-{{version}}/shared/config/"
        recurse: yes
        patterns: "*yml"
      register: yml_to_copy

    - name: Copy to the new application directory
      copy:
        src: "{{ item.path }}"
        dest: "/home/deploy/erp-{{env}}/shared/config/"
        remote_src: yes
      with_items: "{{ yml_to_copy.files }}"

    - name: Ansible check directory.
      stat:
        path: /home/deploy/erp-{{env}}/shared/config/credentials
      register: credentials

    - name: "echo if directory already existed"
      debug:
        msg: "credentials directory is already existed"
      when: credentials.stat.exists

    - name: "Ansible create directory if not exists"
      file:
        path: /home/deploy/erp-{{env}}/shared/config/credentials
        state: directory
        mode: 0755
        group: deploy
        owner: deploy
      when: credentials.stat.exists == false

    - name: Copying the Directory and its contents
      copy:
        src: ~/Documents/apps/vertilux-accpac/config/credentials/{{env}}.key
        dest: /home/deploy/erp-{{env}}/shared/config/credentials
        owner: deploy
        group: deploy
