---
- hosts: web_servers
  remote_user: deploy

  pre_tasks:
    - pause:
        prompt: |
          Select environment:
          1- accltd
          2- bzidat
          3- covdat
          4- espdat
          5- mxpdat
          6- prndat
          7- pwcdat
          8- rdmdat
          9- saldat
          10- wcpdat
      when: env is not defined
      register: prompt

    - name: Restart passenger app server
      set_fact:
        env: accltd
      when: env is not defined

  tasks:
  - name: Restart passenger app server
    command: /bin/bash -l -c  'touch /home/deploy/erp-{{env}}/current/tmp/restart.txt'
    when: env is defined
