---
- hosts: web_servers
  become: yes

  pre_tasks:
    - pause:
        prompt: |
          Select environment:
          1- accltd
          2- bzidat
          3- covdat
          4- espdat
          5- mxpdat
          6- prndat
          7- pwcdat
          8- rdmdat
          9- saldat
          10- wcpdat
      when: env is not defined
      register: prompt

    - name: Restart queue processing job
      set_fact:
        env: accltd
      when: env is not defined

  tasks:
    - name: Restart queue processing job Sidekiq
      service:
        name: "sidekiq-{{env}}"
        state: restarted
      when: env is defined
