---
# tasks file for set-sidekiq-service
- block: 
  - name: Create service file
    template:
      src: sidekiq.service.j2
      dest: /lib/systemd/system/sidekiq-{{env}}.service
  - name: Started service
    service:
      name: sidekiq-{{env}}.service
      state: started
  - name: Enabled service
    service:
      name: sidekiq-{{env}}.service
      enabled: yes
  become: yes
