---
- hosts: web_servers
  remote_user: deploy

  vars_prompt:
    - name: env
      prompt: "Please enter environment"
      private: no
    - name: port
      prompt: "Please enter SQL server port"
      private: no

  tasks:
  - name: Replace postgres DB name
    replace:
      path: "/home/deploy/erp-{{env}}/shared/config/database_postgres.yml"
      regexp: '{{replace}}'
      replace: "{{with}}"
    tags:
       - postgres

  - name: "Replace sql server default's yml port"
    replace:
      path: "/home/deploy/erp-{{env}}/shared/config/database.yml"
      regexp: '55200'
      replace: "{{port}}"
    tags:
       - sql_server

  - name: "Replace port on sql server config yml file"
    replace:
      path: "/home/deploy/erp-{{env}}/shared/config/database_sqlserver.yml"
      regexp: '55200'
      replace: "{{port}}"
    tags:
       - sql_server
