---
- hosts: all
  tasks:
    - name: Run ruby script to scrap LME/SMM
      command: /bin/bash -l -c  'cd /home/deploy/scraper && ruby scraper.rb'
      environment:
        PATH: "/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/bin:/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/shims:/home/deploy/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/sbin:/bin:/usr/games"
