---
- name: Check Passenger workers and queue
  hosts: app_servers
  gather_facts: yes
  become: yes

  vars:
    queue_threshold: 10
    slack_webhook_url: "{{ SLACK_WEBHOOK_URL | default('') }}"

  tasks:

    # --- QUEUE STATUS ---
    - name: Read Passenger queue
      command: passenger-status
      register: queue_raw

    - name: Parse queue value (cast to INT)
      set_fact:
        queue_size: "{{ queue_raw.stdout
                        | regex_search('Requests in top-level queue\\s*:\\s*(\\d+)', '\\1')
                        | int }}"

    # --- EXTRA SNAPSHOT INFO ---

    - name: Get memory usage (free -h)
      command: free -h
      register: mem_info
      changed_when: false

    - name: Extract available memory (numeric GB/MB)
      set_fact:
        mem_available: "{{ mem_info.stdout
                          | regex_search('Mem:\\s+\\S+\\s+\\S+\\s+\\S+\\s+\\S+\\s+\\S+\\s+(\\S+)', '\\1') }}"

    - name: Get passenger memory stats
      command: passenger-memory-stats
      register: p_mem
      changed_when: false

    - name: Extract total Passenger dirty RSS
      set_fact:
        passenger_total_rss: "{{ p_mem.stdout
                                 | regex_search('Total private dirty RSS:\\s*([0-9\\.]+\\s*[A-Z]+)', '\\1') }}"

    # --- SEND SLACK SNAPSHOT ---
    - name: Send Slack snapshot summary
      uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: |
            :desktop_computer: *Snapshot — {{ inventory_hostname }}*
            • Queue: {{ queue_size }}
            • Threshold: {{ queue_threshold }}

            *Memory (free -h):*
            {{ mem_info.stdout }}

            *Passenger memory stats (summary):*
            Total Passenger RSS: {{ passenger_total_rss }}

            *Quick view:*
            - Available system memory: {{ mem_available }}
            - Passenger total memory: {{ passenger_total_rss }}
            - Processes inspected: {{ (p_mem.stdout | regex_search('Processes:\\s*(\\d+)', '\\1')) }}

      changed_when: false
      ignore_errors: true
