---
- name: Check Passenger workers and queue
  hosts: app_servers
  gather_facts: false
  become: yes
  serial: 1

  vars:
    passenger_queue_threshold: 10
    slack_webhook_url: "{{ SLACK_WEBHOOK_URL | default('') }}"

  tasks:

    # ---- COLLECT RAW DATA ----
    - name: Run passenger-status
      command: passenger-status
      register: passenger_status
      changed_when: false

    - name: Run passenger-status (XML for parsing)
      command: passenger-status --show=xml
      register: passenger_xml
      changed_when: false

    - name: Run passenger-memory-stats
      command: passenger-memory-stats
      register: p_mem
      changed_when: false

    - name: Check free memory
      command: free -h
      register: mem
      changed_when: false

    # ---- PARSE USEFUL VALUES ----
    - name: Extract Passenger queue
      set_fact:
        passenger_queue: "{{ passenger_status.stdout
                             | regex_search('Requests in top-level queue\\s*:\\s*(\\d+)', '\\1')
                             | default('0')
                             | int }}"

    - name: Extract Available memory
      set_fact:
        mem_available: "{{ mem.stdout_lines
                           | select('search', 'Mem:')
                           | list
                           | first
                           | split()
                           | last }}"

    # CAMBIO AQUI: Usamos regex_findall + last para obtener el bloque final (Passenger) y no el primero (Nginx)
    - name: Extract Passenger total RSS
      set_fact:
        passenger_total_rss: "{{ p_mem.stdout
                                 | regex_findall('Total private dirty RSS:\\s*([0-9\\.]+\\s*MB)')
                                 | last
                                 | default('0 MB') }}"

    # CAMBIO AQUI: Usamos regex_findall + last para obtener el conteo final (Passenger)
    - name: Extract Passenger processes count
      set_fact:
        passenger_proc_count: "{{ p_mem.stdout
                                  | regex_findall('### Processes:\\s*(\\d+)')
                                  | last
                                  | default('0')
                                  | int }}"

    # ---- SEND SNAPSHOT TO SLACK ----
    - name: Send snapshot to Slack
      when: slack_webhook_url | length > 0
      uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: |-
            :desktop_computer: *Snapshot — {{ inventory_hostname }}*
            • Queue: {{ passenger_queue }}
            • Threshold: {{ passenger_queue_threshold }}

            *Memory (free -h):*
            {{ mem.stdout }}

            *Passenger memory stats:*
            {{ p_mem.stdout }}

            *Summary metrics*
            • Available memory: {{ mem_available }}
            • Passenger dirty RSS total: {{ passenger_total_rss }}
            • Passenger processes: {{ passenger_proc_count }}

      changed_when: false
      ignore_errors: true
