---
- name: Full Passenger + server health snapshot
  hosts: app_servers
  gather_facts: false
  become: yes

  vars:
    slack_webhook_url: "{{ SLACK_WEBHOOK_URL | default('') }}"

  tasks:

    # -------------------- BASIC STATUS -------------------------
    - name: Run passenger-status
      command: passenger-status
      register: passenger_text
      changed_when: false

    - name: Run passenger-memory-stats
      command: passenger-memory-stats
      register: passenger_mem
      changed_when: false

    - name: Check system memory
      command: free -h
      register: mem_free
      changed_when: false

    - name: Check uptime & load
      command: uptime
      register: uptime_cmd
      changed_when: false

    - name: Count active connections
      command: netstat -nat | grep ESTABLISHED | wc -l
      register: conn_count
      changed_when: false

    # -------------------- KEY METRICS -------------------------
    - name: Extract queue size
      set_fact:
        status_queue: "{{ passenger_text.stdout
                          | regex_search('Requests in top-level queue\\s*:\\s*(\\d+)', '\\1')
                          | default('0') | int }}"

    - name: Extract total processes
      set_fact:
        status_procs: "{{ passenger_text.stdout
                          | regex_search('Processes\\s*:\\s*(\\d+)', '\\1')
                          | default('0') | int }}"

    - name: Show snapshot in AWX output
      debug:
        msg: |
          ========= SNAPSHOT {{ inventory_hostname }} =========
          passenger-status:
          {{ passenger_text.stdout }}

          passenger-memory-stats:
          {{ passenger_mem.stdout }}

          free -h:
          {{ mem_free.stdout }}

          uptime:
          {{ uptime_cmd.stdout }}

    # -------------------- SLACK SNAPSHOT ----------------------
    - name: Send Slack snapshot summary
      when: slack_webhook_url | length > 0
      uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: |
            🩺 *Server snapshot — {{ inventory_hostname }}*
            • Queue: {{ status_queue }}
            • Processes: {{ status_procs }}
            • Established connections: {{ conn_count.stdout }}
            • Uptime / Load: `{{ uptime_cmd.stdout }}`

            _Details (memory + full passenger output) are in the AWX job log._
      changed_when: false
      ignore_errors: true
