---
- name: Clean cached and log files on all app servers and compare disk usage
  hosts: app_servers
  become: yes
  gather_facts: no

  vars:
    apps:
      - erp-accltd
      - erp-bzidat
      - erp-espdat
      - erp-mxpdat
      - erp-pwcdat
      - erp-rdmdat
      - erp-saldat
    keep_logs_days: 14   # Días de retención de logs

  tasks:
    # --- DISK STATUS BEFORE CLEANUP ---
    - name: Capture disk usage before cleanup
      command: df -h --output=source,size,used,avail,pcent,target -x tmpfs -x devtmpfs
      register: disk_before

    - name: Show disk usage before cleanup
      debug:
        msg: |
           Disk usage BEFORE cleanup on {{ inventory_hostname }}:
          {{ disk_before.stdout_lines | join('\n') }}

    # --- CLEAN CACHE FILES ---
    - name: Remove cached files (tmp/cache)
      file:
        path: "/home/deploy/{{ item }}/current/tmp/cache"
        state: absent
      loop: "{{ apps }}"
      ignore_errors: yes
      register: cache_cleanup

    - name: Recreate cache directories
      file:
        path: "/home/deploy/{{ item }}/current/tmp/cache"
        state: directory
        owner: deploy
        group: deploy
        mode: '0755'
      loop: "{{ apps }}"

    # --- CLEAN OLD LOGS ---
    - name: Find old log files (older than {{ keep_logs_days }} days)
      find:
        paths: "/home/deploy/{{ item }}/current/log"
        age: "{{ keep_logs_days }}d"
        recurse: yes
      loop: "{{ apps }}"
      register: old_logs

    - name: Delete found old log files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ old_logs.results | map(attribute='files') | flatten(levels=1) | list }}"
      when: old_logs.results | length > 0
      ignore_errors: yes

    # --- DISK STATUS AFTER CLEANUP ---
    - name: Capture disk usage after cleanup
      command: df -h --output=source,size,used,avail,pcent,target -x tmpfs -x devtmpfs
      register: disk_after

    - name: Show disk usage after cleanup
      debug:
        msg: |
           Disk usage AFTER cleanup on {{ inventory_hostname }}:
          {{ disk_after.stdout_lines | join('\n') }}

    # --- COMPARE AND SUMMARIZE ---
    - name: Show cleanup summary and comparison
      debug:
        msg: |
           Cleanup completed on {{ inventory_hostname }}
           Caches cleared for {{ cache_cleanup.results | length }} apps
           Logs removed: {{ old_logs.results | length }} app folders checked
          
           DISK USAGE COMPARISON:
          BEFORE:
          {{ disk_before.stdout_lines | join('\n') }}
          AFTER:
          {{ disk_after.stdout_lines | join('\n') }}
