- hosts: all
  tasks:
  - name: Get all original config files
    find: 
      paths: "/home/deploy/erp-accltd/shared/config/"
      recurse: yes
      patterns: "*yml"
    register: yml_to_copy
  - name: Copy to the new application directory
    copy: src={{ item.path }} dest=/home/deploy/erp-{{env}}/shared/config/
      with_items: "{{ yml_to_copy.files }}"

  - name: Get all yml config files
    find:  
      paths: "/home/deploy/erp-{{env}}/shared/config/"
      patterns: "*.yml"
    register: yml_config

  - name: Replace environment name
    replace:
      dest: "{{ item.path }}"
      backup: yes
      regexp: 'accltd'
      replace: "{{env}}"
    with_items: "{{ yml_config.files }}"

  - name: Replace DB name
    replace:
      dest: "{{ item.path }}"
      backup: yes
      regexp: 'ACCLTD'
      replace: "{{env | upper}}"
    with_items: "{{ yml_config.files }}"
