# Archivo: disconnect_single_vm_net.yml
---
- name: "1. Confirmar destino (VM: {{ vm_name | upper }}, Nodo: {{ vm_pve_node_name }})"
  ansible.builtin.debug:
    msg: "Desconectando red de {{ vm_name }} (ID: {{ vm_vmid }}) en nodo PVE: {{ vm_pve_node_name }} ({{ pve_host_ip }})"

- name: "2. Desconectar tarjeta de red (net0) usando 'qm set'"
  # qm set <vmid> --delete net0: Elimina la configuración de la tarjeta de red (net0).
  # Para re-habilitar, se usa un comando similar con '--net0 model=virtio,bridge=vmbr0'
  ansible.builtin.command: "qm set {{ vm_vmid }} --delete net0"
  delegate_to: "{{ pve_host_ip }}"
  vars:
    ansible_user: root 

- name: "3. Aviso de finalización"
  ansible.builtin.debug:
    msg: "Red de {{ vm_name }} ha sido desconectada."
