---
- name: Dump VM keys for a specific role
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: "target_role"
      prompt: "Enter the role to list (e.g. granite, ts, sql, backup)"
      private: no

  tasks:
    - name: Filter keys by role={{ target_role }}
      debug:
        msg: >-
          {{
            proxmox_vms
            | dict2items
            | selectattr('value.role','equalto', target_role)
            | map(attribute='key')
            | list | sort | join('\n')
          }}
