---
- name: List VM keys for a given role (uses Survey)
  hosts: pve
  gather_facts: false
  run_once: true

  vars:
    # Survey: text o multiple-choice (ej: granite, ts, etc.)
    target_role: "{{ target_role | default('granite') }}"

  tasks:
    - name: Collect keys for role={{ target_role }}
      delegate_to: localhost
      set_fact:
        _vm_keys_by_role: >-
          {{
            proxmox_vms
            | dict2items
            | selectattr('value.role','defined')
            | selectattr('value.role','equalto', target_role)
            | map(attribute='key')
            | list | sort
          }}

    # OPCIÓN A: salida “linda”, una por línea
    - name: Pretty list (one per line)
      delegate_to: localhost
      debug:
        msg: "{{ item }}"
      loop: "{{ _vm_keys_by_role }}"
