---
- name: List VM keys for a given role (uses Survey)
  hosts: pve            # así cargamos las group_vars del grupo pve
  gather_facts: false
  run_once: true        # se ejecuta una sola vez
  vars:
    # lo setea el Survey; aquí solo damos un respaldo por si acaso
    target_role: "{{ target_role | default('granite') }}"

  tasks:
    - name: Show keys for role={{ target_role }}
      delegate_to: localhost
      debug:
        msg: >-
          {{
            proxmox_vms
            | dict2items
            | selectattr('value.role','equalto', target_role)
            | map(attribute='key')
            | list | sort
            | join('\n')
          }}
