- hosts: all
  tasks:
  - stat:
      path: /home/deploy/vertilux-accpac/current/tmp/maintenance.yml
    register: result

  - block:
    - debug:
        msg: "ERP maintenance mode is OFF"
    # Setting rails app to maintenance mode
    - name: setting web servers to maintenance mode to ON
      command: /bin/bash -l -c 'cd /home/deploy/{{app}}/current && bundle exec rake RAILS_ENV={{env}} maintenance:start'
      environment:
        PATH: "/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/bin:/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/shims:/home/deploy/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/sbin:/bin:/usr/games"
    when: result.stat.exists == false

  - block:
    - debug:
        msg: "ERP maintenance mode is ON"
    # Setting rails app to maintenance mode
    - name: setting web servers to maintenance mode to OFF
      command: /bin/bash -l -c 'cd /home/deploy/{{app}}/current && bundle exec rake RAILS_ENV={{env}} maintenance:end'
      environment:
        PATH: "/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/bin:/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/shims:/home/deploy/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/sbin:/bin:/usr/games"
    when: result.stat.exists == true
