---
- name: "ERP Vertilux - Reindex Elasticsearch (Searchkick)"
  hosts: all
  become: yes
  become_user: deploy
  gather_facts: yes
  # Ejecuta solo en 1 servidor para no sobrecargar el cluster de Elastic
  run_once: true

  tasks:
    # PASO CRÍTICO: Normalización de variables
    # Este paso busca si la variable viene como 'tenant_code' (Nuevo) O 'tenant_selection' (Viejo)
    # y asigna el valor encontrado a 'actual_tenant'.
    - name: "0. Detectar variable del Survey (Compatibilidad)"
      set_fact:
        actual_tenant: "{{ tenant_code | default(tenant_selection) | default('') }}"

    - name: "1. Validar recepción de datos"
      fail:
        msg: "ERROR: No se recibió el código de la compañía. Verifica que el Survey en AWX esté en ON y que la variable se llame 'tenant_code' o 'tenant_selection'."
      when: actual_tenant == ''

    - name: "2. Configurar rutas dinámicas"
      set_fact:
        # Construye la ruta basada en la evidencia que me diste: /home/deploy/erp-pwcdat/current
        app_base_path: "/home/deploy/erp-{{ actual_tenant }}/current"
        # El RAILS_ENV es el mismo código del tenant (ej. pwcdat)
        rails_env_name: "{{ actual_tenant }}"

    - name: "3. Validar que el directorio existe en el servidor"
      stat:
        path: "{{ app_base_path }}"
      register: dir_check

    - name: "4. Detener si la carpeta no existe (Seguridad)"
      fail:
        msg: "El directorio {{ app_base_path }} no existe en el servidor {{ inventory_hostname }}. Verifica que el código '{{ actual_tenant }}' sea correcto."
      when: not dir_check.stat.exists

    - name: "5. Confirmar inicio de tarea"
      debug:
        msg: "Iniciando reindexación para: {{ rails_env_name }} en {{ app_base_path }}"

    # Ejecutamos el reindex usando el entorno de rbenv y bundle exec
    - name: "6. Ejecutar Rake Task: searchkick:reindex:all"
      shell: |
        export RAILS_ENV={{ rails_env_name }}
        export PATH="/home/deploy/.rbenv/bin:/home/deploy/.rbenv/shims:$PATH"
        eval "$(rbenv init -)"
        bundle exec rake searchkick:reindex:all
      args:
        chdir: "{{ app_base_path }}"
      async: 1800 # 30 minutos de timeout
      poll: 15
      register: reindex_result

    - name: "7. Resultado de la Reindexación"
      debug:
        msg: "{{ reindex_result.stdout_lines }}"
