---
- name: "ERP Vertilux - Reindex Elasticsearch (Searchkick)"
  hosts: all
  become: yes
  become_user: deploy
  gather_facts: yes
  # GARANTÍA: Ejecuta solo en 1 servidor (lb01, etc.), nunca en paralelo.
  run_once: true

  tasks:
    # -------------------------------------------------------------------------
    # 1. PREPARACIÓN DE VARIABLES
    # -------------------------------------------------------------------------
    
    # Mantenemos esto SOLO porque es necesario para que AWX no falle con los corchetes ['accltd']
    - name: "1. Normalizar código de compañía"
      set_fact:
        clean_tenant: >-
          {%- if tenant_code is string -%}
          {{ tenant_code }}
          {%- elif tenant_code is sequence and tenant_code | length > 0 -%}
          {{ tenant_code[0] }}
          {%- else -%}
          ''
          {%- endif -%}

    # Validamos que se haya seleccionado algo en el Survey
    - name: "2. Validar datos de entrada"
      fail:
        msg: "ERROR: Faltan datos. Asegúrese de seleccionar Compañía y Clase en el Survey."
      when: 
        - clean_tenant == '' or clean_tenant is undefined
        - target_class is undefined or target_class == ''

    # Configuramos las rutas limpias
    - name: "3. Configurar entorno de ejecución"
      set_fact:
        app_path: "/home/deploy/erp-{{ clean_tenant }}/current"
        rails_env: "{{ clean_tenant }}"

    # -------------------------------------------------------------------------
    # 2. EJECUCIÓN "LEGACY" (Versión Original y Estable)
    # -------------------------------------------------------------------------
    # Sin parches, sin scripts extra. Solo el comando que funcionó manualmente.
    
    - name: "4. Reindexing {{ target_class }} for {{ rails_env }}"
      command: >-
        /bin/bash -l -c 'cd {{ app_path }} && bundle exec rake RAILS_ENV={{ rails_env }} searchkick:reindex CLASS={{ target_class }}'
      environment:
        # PATH exacto del sistema antiguo para máxima compatibilidad
        PATH: "/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/bin:/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/shims:/home/deploy/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/sbin:/bin:/usr/games"
      register: reindex_result

    - name: "5. Resultado Final"
      debug:
        msg: "{{ reindex_result.stdout_lines }}"
