---
- name: "ERP Vertilux - Reindex Elasticsearch (Searchkick)"
  hosts: all
  become: yes
  become_user: deploy
  gather_facts: yes
  # GARANTÍA: Ejecuta solo en 1 servidor.
  run_once: true

  tasks:
    # 1. Normalización
    - name: "1. Normalizar código de compañía"
      set_fact:
        clean_tenant: >-
          {%- if tenant_code is string -%}
          {{ tenant_code }}
          {%- elif tenant_code is sequence and tenant_code | length > 0 -%}
          {{ tenant_code[0] }}
          {%- else -%}
          ''
          {%- endif -%}

    # 2. Validación
    - name: "2. Validar datos de entrada"
      fail:
        msg: "ERROR: Faltan datos. Asegúrese de seleccionar Compañía y Clase en el Survey."
      when: 
        - clean_tenant == '' or clean_tenant is undefined
        - target_class is undefined or target_class == ''

    # 3. Configuración
    - name: "3. Configurar entorno de ejecución"
      set_fact:
        app: "erp-{{ clean_tenant }}"
        env: "{{ clean_tenant }}"
        class_to_reindex: "{{ target_class }}"

    # --- NUEVO PASO: AUTO-REPARACIÓN DE CÓDIGO ---
    # Este paso corrige el bug en ShippingReference que causa el crash por usuarios borrados.
    # Cambia 'User.find(user_id)' (estricto) por 'User.find_by(id: user_id).try(:fname)' (seguro).
    - name: "3.5 Hotfix: Parchear bug de usuario no encontrado (ShippingReference)"
      command: >-
        sed -i 's/User.find(user_id).fname/User.find_by(id: user_id).try(:fname)/g' app/models/shipping_reference.rb
      args:
        chdir: "/home/deploy/{{ app }}/current"
      # Solo ejecutamos esto si la clase es ShippingReference, aunque no hace daño correrlo siempre.
      when: class_to_reindex == 'ShippingReference'
      ignore_errors: yes 

    # 4. EJECUCIÓN
    - name: "4. Reindexing {{ class_to_reindex }} for {{ env }}"
      command: >-
        /bin/bash -l -c 'cd /home/deploy/{{app}}/current && bundle exec rake RAILS_ENV={{env}} searchkick:reindex CLASS={{class_to_reindex}}'
      environment:
        PATH: "/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/bin:/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/shims:/home/deploy/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/sbin:/bin:/usr/games"
      register: reindex_result

    - name: "5. Resultado Final"
      debug:
        msg: "{{ reindex_result.stdout_lines }}"
