---
- name: "ERP Vertilux - Reindex Elasticsearch (Searchkick)"
  hosts: all
  become: yes
  become_user: deploy
  gather_facts: yes
  # GARANTÍA: Ejecuta solo en 1 servidor, nunca en paralelo.
  run_once: true

  tasks:
    # 1. Normalización de variable (Vital para que el Survey funcione)
    - name: "1. Normalizar código de compañía"
      set_fact:
        clean_tenant: >-
          {%- if tenant_code is string -%}
          {{ tenant_code }}
          {%- elif tenant_code is sequence and tenant_code | length > 0 -%}
          {{ tenant_code[0] }}
          {%- else -%}
          ''
          {%- endif -%}

    # 2. Validación
    - name: "2. Validar variable obligatoria"
      fail:
        msg: "ERROR: La variable 'tenant_code' está vacía. Revise el Survey."
      when: clean_tenant == '' or clean_tenant is undefined

    # 3. Definición de variables para el comando Legacy
    - name: "3. Configurar variables"
      set_fact:
        # Mapeamos a las variables que usaba el script antiguo para claridad
        app_name: "erp-{{ clean_tenant }}"
        env_name: "{{ clean_tenant }}"

    # 4. EJECUCIÓN MODO LEGACY (Tower Antiguo)
    # Usamos exactamente el PATH y la estructura de comando del sistema anterior.
    # Nota: Usamos searchkick:reindex:all para cubrir toda la empresa, ya que 
    # la instrucción es no pedir clases específicas.
    - name: "4. Reindexing elasticsearch (Legacy Style)"
      command: >-
        /bin/bash -l -c 'cd /home/deploy/{{ app_name }}/current && bundle exec rake RAILS_ENV={{ env_name }} searchkick:reindex:all'
      environment:
        # PATH exacto del sistema antiguo
        PATH: "/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/bin:/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/shims:/home/deploy/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/sbin:/bin:/usr/games"
        # Mantenemos estas protecciones por si acaso, no hacen daño y evitan el timeout
        NEW_RELIC_AGENT_ENABLED: "false"
        DISABLE_SPRING: "1"
      register: reindex_result

    - name: "5. Resultado Final"
      debug:
        msg: "{{ reindex_result.stdout_lines }}"
