---
- name: "ERP Vertilux - Reindex Elasticsearch (Searchkick)"
  hosts: all
  become: yes
  become_user: deploy
  gather_facts: yes
  # GARANTÍA: Ejecuta solo en 1 servidor.
  run_once: true

  tasks:
    # 1. Normalización
    - name: "1. Normalizar código de compañía"
      set_fact:
        clean_tenant: >-
          {%- if tenant_code is string -%}
          {{ tenant_code }}
          {%- elif tenant_code is sequence and tenant_code | length > 0 -%}
          {{ tenant_code[0] }}
          {%- else -%}
          ''
          {%- endif -%}

    # 2. Validación
    - name: "2. Validar datos de entrada"
      fail:
        msg: "ERROR: Faltan datos. Asegúrese de seleccionar Compañía y Clase en el Survey."
      when: 
        - clean_tenant == '' or clean_tenant is undefined
        - target_class is undefined or target_class == ''

    # 3. Configuración
    - name: "3. Configurar entorno de ejecución"
      set_fact:
        app: "erp-{{ clean_tenant }}"
        env: "{{ clean_tenant }}"
        class_to_reindex: "{{ target_class }}"

    # --- HOTFIXES DE INGENIERÍA: LIMPIEZA DE CÓDIGO Y DATOS ---
    # 1. Parcheamos User/Type para que no falle si el ID no existe.
    # 2. Parcheamos campos de texto (Granite/Description) con .to_s.squish para eliminar saltos de línea corruptos que rompen el JSON.
    - name: "3.5 Hotfix: Parchear bugs de IDs y Sanitizar Textos"
      shell: |
        # Fix 1: IDs Huérfanos (User y ReferenceType)
        sed -i 's/User.find(user_id).fname/User.find_by(id: user_id).try(:fname)/g' app/models/shipping_reference.rb
        sed -i 's/ShippingReferenceType.find(shipping_reference_type_id).name/ShippingReferenceType.find_by(id: shipping_reference_type_id).try(:name)/g' app/models/shipping_reference.rb
        
        # Fix 2: Sanitización de Datos (Eliminar saltos de línea \n que causan Error 400 Malformed JSON)
        # Limpiamos customer_namer (Descripción del partner)
        sed -i 's/pluck(:TradingPartnerDescription).first/pluck(:TradingPartnerDescription).first.to_s.squish/g' app/models/shipping_reference.rb
        # Limpiamos granite_document (Array de Números)
        sed -i 's/pluck(:Number)/pluck(:Number).map(&:to_s).map(&:squish)/g' app/models/shipping_reference.rb
      args:
        chdir: "/home/deploy/{{ app }}/current"
      # Solo ejecutamos esto si la clase es ShippingReference
      when: class_to_reindex == 'ShippingReference'
      ignore_errors: yes 

    # 4. EJECUCIÓN (Super Segura: BATCH 50 + UTF-8)
    # Bajamos el BATCH a 50 para máxima estabilidad en datos sucios.
    - name: "4. Reindexing {{ class_to_reindex }} for {{ env }}"
      command: >-
        /bin/bash -l -c 'cd /home/deploy/{{app}}/current && bundle exec rake RAILS_ENV={{env}} searchkick:reindex CLASS={{class_to_reindex}} BATCH=50'
      environment:
        PATH: "/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/bin:/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/shims:/home/deploy/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/sbin:/bin:/usr/games"
        # Forzar encoding para evitar crashes por caracteres extraños en la DB
        LC_ALL: "en_US.UTF-8"
        LANG: "en_US.UTF-8"
      register: reindex_result

    - name: "5. Resultado Final"
      debug:
        msg: "{{ reindex_result.stdout_lines }}"
