---
- name: "ERP Vertilux - Reindex Elasticsearch (Searchkick)"
  hosts: all
  become: yes
  become_user: deploy
  gather_facts: yes
  # GARANTÍA: Ejecuta solo en 1 servidor. Al ser índice compartido, basta con uno.
  run_once: true

  tasks:
    # -------------------------------------------------------------------------
    # 1. PREPARACIÓN DE VARIABLES
    # -------------------------------------------------------------------------
    
    # Normalizamos el código de compañía (quita corchetes si AWX los envía)
    - name: "1. Normalizar código de compañía"
      set_fact:
        clean_tenant: >-
          {%- if tenant_code is string -%}
          {{ tenant_code }}
          {%- elif tenant_code is sequence and tenant_code | length > 0 -%}
          {{ tenant_code[0] }}
          {%- else -%}
          ''
          {%- endif -%}

    # Validamos que se haya seleccionado algo
    - name: "2. Validar datos de entrada"
      fail:
        msg: "ERROR: Faltan datos. Asegúrese de seleccionar Compañía y Clase en el Survey."
      when: 
        - clean_tenant == '' or clean_tenant is undefined
        - target_class is undefined or target_class == ''

    # Configuramos las variables para el comando
    - name: "3. Configurar entorno de ejecución"
      set_fact:
        app: "erp-{{ clean_tenant }}"
        env: "{{ clean_tenant }}"
        # target_class viene directo del nuevo Survey (ej. ShippingReference)
        class_to_reindex: "{{ target_class }}"

    # -------------------------------------------------------------------------
    # 2. EJECUCIÓN "LEGACY" (La versión rápida y probada)
    # -------------------------------------------------------------------------
    
    - name: "4. Reindexing {{ class_to_reindex }} for {{ env }}"
      # Usamos /bin/bash -l -c para cargar el perfil completo de 'deploy'.
      # Esto replica exactamente tu prueba manual exitosa en el servidor.
      command: >-
        /bin/bash -l -c 'cd /home/deploy/{{app}}/current && bundle exec rake RAILS_ENV={{env}} searchkick:reindex CLASS={{class_to_reindex}}'
      environment:
        # PATH idéntico al Tower antiguo para máxima compatibilidad
        PATH: "/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/bin:/home/deploy/.rbenv/plugins/ruby-build/bin:/home/deploy/.rbenv/shims:/home/deploy/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/sbin:/bin:/usr/games"
      register: reindex_result

    - name: "5. Resultado Final"
      debug:
        msg: "{{ reindex_result.stdout_lines }}"
