---
- name: "ERP Vertilux - Reindex Elasticsearch (Searchkick)"
  hosts: all
  become: yes
  become_user: deploy
  gather_facts: yes
  # GARANTÍA: Ejecuta solo en 1 servidor, nunca en paralelo.
  # Al ser un índice compartido, correrlo en LB01 ya actualiza para LB02, LB03 y LB04.
  run_once: true

  tasks:
    # 1. Normalización estricta de la variable tenant_code
    # Si AWX envía ['pwcdat'] (lista) lo convierte a 'pwcdat' (texto).
    - name: "1. Normalizar código de compañía"
      set_fact:
        clean_tenant: >-
          {%- if tenant_code is string -%}
          {{ tenant_code }}
          {%- elif tenant_code is sequence and tenant_code | length > 0 -%}
          {{ tenant_code[0] }}
          {%- else -%}
          ''
          {%- endif -%}

    # 2. Validación de Seguridad
    - name: "2. Validar variable obligatoria"
      fail:
        msg: "ERROR: La variable 'tenant_code' está vacía o no definida en el Survey."
      when: clean_tenant == '' or clean_tenant is undefined

    # 3. Definición de Rutas
    - name: "3. Configurar entorno"
      set_fact:
        app_path: "/home/deploy/erp-{{ clean_tenant }}/current"
        rails_env: "{{ clean_tenant }}"

    # 4. Verificación de Carpeta
    - name: "4. Verificar existencia del directorio"
      stat:
        path: "{{ app_path }}"
      register: dir_check

    - name: "5. Abortar si no existe la carpeta"
      fail:
        msg: "CRÍTICO: El directorio {{ app_path }} no existe. Verifique el código '{{ clean_tenant }}'."
      when: not dir_check.stat.exists

    # 5. Ejecución Síncrona (Sin 'async' para evitar spam en el log)
    - name: "6. Ejecutar Reindexación Completa (Espere a que finalice)"
      shell: |
        export RAILS_ENV={{ rails_env }}
        # OPTIMIZACIÓN CRÍTICA:
        # 1. Desactivamos NewRelic para evitar que el monitoreo cuelgue el proceso (Timeout error).
        # 2. Desactivamos Spring para forzar un arranque limpio de Rails.
        export NEW_RELIC_AGENT_ENABLED=false
        export DISABLE_SPRING=1
        
        export PATH="/home/deploy/.rbenv/bin:/home/deploy/.rbenv/shims:$PATH"
        eval "$(rbenv init -)"
        
        echo "Iniciando reindexado para {{ rails_env }}..."
        bundle exec rake searchkick:reindex:all
      args:
        chdir: "{{ app_path }}"
      # Sin async ni poll: Ansible esperará pacientemente hasta que termine.
      register: reindex_result

    - name: "7. Resultado Final"
      debug:
        msg: "{{ reindex_result.stdout_lines }}"
