---
- name: Restart Elasticsearch on legacy host
  hosts: production_db
  become: yes
  gather_facts: no

  vars:
    es_host: 104.236.33.109
    es_port: 9200

  tasks:
    - name: Restart ES via SysV service
      service:
        name: elasticsearch
        state: restarted

    - name: Wait for TCP port
      wait_for:
        host: "{{ es_host }}"
        port: "{{ es_port }}"
        delay: 1
        timeout: 60

    - name: Health check
      uri:
        url: "http://{{ es_host }}:{{ es_port }}/"
        method: GET
        return_content: yes
      register: es_banner

    - debug:
        msg: "ES ok: {{ es_banner.content | default('no content') | truncate(200) }}"
