---
- name: Restart selected DigitalOcean droplets (sequential) and notify Slack
  hosts: digital_ocean     # grupo del inventario (ver sección 3)
  gather_facts: no
  serial: 1                # uno por uno
  any_errors_fatal: false

  vars:
    # AWX Survey: variable multiple-select con los hostnames/IPs elegidos
    selected_droplets: "{{ survey_droplets | default([]) }}"
    # Slack webhook viene de la credencial "Slack Webhook" (variable SLACK_WEBHOOK_URL)
    slack_webhook_url: "{{ SLACK_WEBHOOK_URL | default(omit) }}"
    # Acumuladores globales (se actualizan en localhost)
    restarted_ok: []
    restarted_fail: []

  pre_tasks:
    - name: Validate survey provided at least one droplet
      ansible.builtin.assert:
        that:
          - selected_droplets | length > 0
        fail_msg: "❌ You must select at least one droplet in the survey."
        success_msg: "✅ Selected: {{ selected_droplets | join(', ') }}"
      run_once: true
      delegate_to: localhost

    - name: Notify start on Slack
      ansible.builtin.uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: "⚙️ Starting sequential reboot for: {{ selected_droplets | join(', ') }}"
      run_once: true
      delegate_to: localhost
      when: slack_webhook_url is defined
      ignore_errors: true

  tasks:
    - name: Skip hosts not selected in survey
      ansible.builtin.meta: end_host
      when: inventory_hostname not in selected_droplets

    - name: Announce host start (Slack)
      ansible.builtin.uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: "🔄 Rebooting *{{ inventory_hostname }}*…"
      delegate_to: localhost
      when: slack_webhook_url is defined
      ignore_errors: true

    - name: Reboot droplet (wait until it’s back)
      become: true
      become_method: sudo
      # el usuario SSH lo pones en inventario/credencial (deploy)
      ansible.builtin.reboot:
        pre_reboot_delay: 0
        post_reboot_delay: 10
        reboot_timeout: 900
        test_command: "whoami"

    - name: Mark success
      ansible.builtin.set_fact:
        restarted_ok: "{{ restarted_ok + [inventory_hostname] }}"
      delegate_to: localhost

    - name: Pause 30s before next host
      ansible.builtin.pause:
        seconds: 30

  rescue:
    - name: Mark failure
      ansible.builtin.set_fact:
        restarted_fail: "{{ restarted_fail + [inventory_hostname] }}"
      delegate_to: localhost

    - name: Announce host failure (Slack)
      ansible.builtin.uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: "❗ Reboot FAILED on *{{ inventory_hostname }}*"
      delegate_to: localhost
      when: slack_webhook_url is defined
      ignore_errors: true

    - name: Pause 30s before next host (after failure)
      ansible.builtin.pause:
        seconds: 30

  always:
    - name: Final Slack summary
      ansible.builtin.uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: >-
            ✅ Rebooted: {{ (restarted_ok | default([])) | unique | join(', ') | default('none') }}
            {% if (restarted_fail | default([])) | length > 0 %}
            ❌ Failed: {{ restarted_fail | unique | join(', ') }}
            {% endif %}
      run_once: true
      delegate_to: localhost
      when: slack_webhook_url is defined
      ignore_errors: true
