---
- name: Restart Nginx on production app servers (one by one)
  hosts: app_servers
  serial: 1
  gather_facts: false
  become: yes

  tasks:

    - block:

        - name: Restart nginx service
          ansible.builtin.systemd:
            name: nginx
            state: restarted
            daemon_reload: yes

        - name: Notify Slack (success)
          ansible.builtin.uri:
            url: "{{ cloud_slack_webhook_url }}"
            method: POST
            body_format: json
            body:
              text: |
                ✅ *Nginx restarted successfully*
                Server: `{{ inventory_hostname }}`
                Environment: `production`
            status_code: [200, 204]

      rescue:

        - name: Notify Slack (failure)
          ansible.builtin.uri:
            url: "{{ cloud_slack_webhook_url }}"
            method: POST
            body_format: json
            body:
              text: |
                ❌ *FAILED restarting Nginx*
                Server: `{{ inventory_hostname }}`
                Environment: `production`
            status_code: [200, 204]

        - name: Fail the play explicitly
          ansible.builtin.fail:
            msg: "Nginx restart failed on {{ inventory_hostname }}"
