---
- name: Restart chosen VPN tunnels on selected UniFi gateway
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # These variables will come from your AWX Survey
    unifi_gateway_ip: "10.255.255.1"
    unifi_api_key: "{{ lookup('env', 'UNIFI_API_KEY') }}"   # Can also come from AWX credential
    selected_vpns: "{{ vpn_list | default(['VXCALUDM']) }}"
    slack_webhook: "{{ lookup('env', 'SLACK_WEBHOOK') }}"
    site: "default"

  tasks:

    - name: Announce start on Slack
      uri:
        url: "{{ slack_webhook }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: ":gear: Starting VPN restart sequence on *{{ site }}* → `{{ selected_vpns | join(', ') }}`"
      delegate_to: localhost

    - name: Pause each VPN tunnel (disable IPsec link)
      uri:
        url: "https://{{ unifi_gateway_ip }}/proxy/network/integration/v1/sites/{{ site }}/vpn/restart"
        method: POST
        headers:
          X-API-KEY: "{{ unifi_api_key }}"
          Accept: "application/json"
          Content-Type: "application/json"
        body_format: json
        body:
          vpn_names: "{{ selected_vpns }}"
          action: "pause"
        validate_certs: false
      register: pause_result
      failed_when: pause_result.status not in [200, 202]

    - name: Wait before resume
      pause:
        seconds: 60

    - name: Resume each VPN tunnel (enable IPsec link)
      uri:
        url: "https://{{ unifi_gateway_ip }}/proxy/network/integration/v1/sites/{{ site }}/vpn/restart"
        method: POST
        headers:
          X-API-KEY: "{{ unifi_api_key }}"
          Accept: "application/json"
          Content-Type: "application/json"
        body_format: json
        body:
          vpn_names: "{{ selected_vpns }}"
          action: "resume"
        validate_certs: false
      register: resume_result
      failed_when: resume_result.status not in [200, 202]

    - name: Notify completion on Slack
      uri:
        url: "{{ slack_webhook }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: ":white_check_mark: VPN restart completed successfully for `{{ selected_vpns | join(', ') }}` on *{{ site }}*."
      when: resume_result.status in [200, 202]
      delegate_to: localhost

    - name: Notify failure on Slack (if any)
      uri:
        url: "{{ slack_webhook }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: ":warning: VPN restart failed for one or more tunnels: `{{ selected_vpns | join(', ') }}`. Please check UniFi logs."
      when: resume_result.status not in [200, 202]
      delegate_to: localhost
