---
- name: Restart selected DigitalOcean droplets sequentially (clean + ordered)
  hosts: localhost
  gather_facts: no

  vars:
    selected_droplets: "{{ survey_droplets | default([]) }}"
    slack_webhook_url: "{{ SLACK_WEBHOOK_URL | default(omit) }}"
    restarted_ok: []
    restarted_fail: []
    start_time: "{{ lookup('pipe', 'date +%s') | int }}"

  pre_tasks:
    - name: Validate survey input
      ansible.builtin.assert:
        that:
          - selected_droplets | length > 0
        fail_msg: "❌ Please select at least one droplet to reboot."
        success_msg: "✅ Selected droplets: {{ selected_droplets | join(', ') }}"

    - name: Notify global start on Slack
      ansible.builtin.uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: >-
            ⚙️ Starting reboot process for: {{ selected_droplets | join(', ') }}
            \nTotal servers: {{ selected_droplets | length }}
      when: slack_webhook_url is defined
      ignore_errors: true

  tasks:
    - name: Process each selected droplet in order
      ansible.builtin.include_tasks: restart-single-droplet.yml
      loop: "{{ selected_droplets }}"
      loop_control:
        loop_var: droplet_name
        index_var: droplet_index

  post_tasks:
    - name: Calculate total duration
      ansible.builtin.set_fact:
        total_duration: "{{ (lookup('pipe', 'date +%s') | int - start_time) | int }}"
        minutes: "{{ (total_duration // 60) | int }}"
        seconds: "{{ (total_duration % 60) | int }}"

    - name: Send final Slack summary
      ansible.builtin.uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: >-
            {% if restarted_fail | length == 0 %}
            ✅ *Reboot Summary (All Successful)*:
            {% else %}
            ⚠️ *Reboot Summary (Partial Failures)*:
            {% endif %}
            - Successful: {{ restarted_ok | join(', ') | default('none') }}
            {% if restarted_fail | length > 0 %}
            - Failed: {{ restarted_fail | join(', ') }}
            {% endif %}
            - ⏱️ Duration: {{ minutes }}m {{ seconds }}s.
            - Total servers processed: {{ (restarted_ok | length + restarted_fail | length) }}
            - Order executed: {% for item in selected_droplets %}{{ loop.index }}️⃣ {{ item }} {% endfor %}
      when: slack_webhook_url is defined
      ignore_errors: true
