---
- name: Restart Nginx on production app servers (one by one)
  hosts: app_servers
  become: yes
  gather_facts: false
  serial: 1        # 👉 reinicia uno por uno

  tasks:

    - name: Restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        daemon_reload: yes
      register: nginx_restart

    - name: Send Slack notification
      ansible.builtin.uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        body_format: json
        body:
          text: |
            :arrows_counterclockwise: *Nginx restarted on* `{{ inventory_hostname }}`
            Status: `{{ 'OK' if nginx_restart is succeeded else 'FAILED' }}`
      when: slack_webhook_url is defined
