---
- name: Restart selected VPN on Miami UDM (via SSH)
  hosts: localhost
  gather_facts: no

  vars:
    udm_ip: 10.255.255.1
    slack_webhook_url: "{{ SLACK_WEBHOOK_URL }}"
    vpn_map:
      VXCALUDM: 67cee99c8580e74ffc44c64f
      VXDLLUDM: 67a26bfa8580e74ffc0ffded
      VXPANUDM: 67ceeb598580e74ffc44c971
      PHILLY-GU: 67a26b268580e74ffc0ffc40
      VTX_SPAIN: 68891f59ccb180797a4bb5e6

  tasks:

    - name: Validate selected VPN
      assert:
        that:
          - survey_vpn is defined
          - vpn_map[survey_vpn] is defined
        success_msg: "✅ Selected VPN: {{ survey_vpn }}"
        fail_msg: "❌ Invalid or undefined VPN selected."

    - name: Send start notification to Slack
      ansible.builtin.uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: "🔄 Starting VPN restart for *{{ survey_vpn }}* on *VXMIAUDMSE*..."
      ignore_errors: true

    - name: Disable selected VPN via SSH (set enabled=false)
      ansible.builtin.shell: >
        curl -sk -X PUT
        -H 'Content-Type: application/json'
        -H 'X-API-KEY: {{ UNIFI_API_KEY }}'
        -d '{"enabled": false}'
        https://127.0.0.1/proxy/network/api/s/default/rest/networkconf/{{ vpn_map[survey_vpn] }}
      delegate_to: "{{ udm_ip }}"
      remote_user: root

    - name: Wait 30 seconds before enabling
      ansible.builtin.pause:
        seconds: 30

    - name: Enable selected VPN via SSH (set enabled=true)
      ansible.builtin.shell: >
        curl -sk -X PUT
        -H 'Content-Type: application/json'
        -H 'X-API-KEY: {{ UNIFI_API_KEY }}'
        -d '{"enabled": true}'
        https://127.0.0.1/proxy/network/api/s/default/rest/networkconf/{{ vpn_map[survey_vpn] }}
      delegate_to: "{{ udm_ip }}"
      remote_user: root

    - name: Send completion notification to Slack
      ansible.builtin.uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: "✅ VPN *{{ survey_vpn }}* on *VXMIAUDMSE* has been restarted successfully after 30 seconds."
      register: slack_result
      ignore_errors: true

    - name: Show Slack response
      debug:
        var: slack_result
      when: slack_result is defined
