---
- name: Restart Nginx on load balancer
  hosts: load_balancer
  gather_facts: false
  become: yes

  tasks:
    - name: Restart Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        daemon_reload: yes
