---
- name: Restart selected VPNs on Miami UDM (via SSH + API)
  hosts: localhost
  gather_facts: no

  vars:
    udm_ip: "10.255.255.1"
    vpn_map:
      PHILLY-GU: "67a26b268580e74ffc0ffc40"
      VTX_SPAIN: "68891f59ccb180797a4bb5e6"
      VXCALUDM: "67cee99c8580e74ffc44c64f"
      VXDLLUDM: "67a26bfa8580e74ffc0ffded"
      VXPANUDM: "67ceeb598580e74ffc44c971"

  tasks:

    - name: Confirm VPNs selected in survey
      assert:
        that:
          - survey_vpn | length > 0
        success_msg: "✅ Selected VPNs: {{ survey_vpn }}"
        fail_msg: "❌ No VPNs selected."

    - name: Notify start on Slack
      ansible.builtin.uri:
        url: "{{ SLACK_WEBHOOK_URL }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: "⚙️ Starting VPN restart process on *Miami UDM* for: {{ survey_vpn | join(', ') }}"
      ignore_errors: true

    - name: Restart each selected VPN sequentially
      ansible.builtin.include_tasks: restart_single_vpn.yml
      loop: "{{ survey_vpn }}"
      loop_control:
        loop_var: vpn_name

    - name: Notify final summary on Slack
      ansible.builtin.uri:
        url: "{{ SLACK_WEBHOOK_URL }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: "🎯 VPN restart process completed for: {{ survey_vpn | join(', ') }}"
      ignore_errors: true
