---
- name: Rolling restart de Sidekiq en app_servers
  hosts: app_servers
  become: yes
  gather_facts: no
  serial: 1   # reinicia host por host

  vars:
    # Patrón de units de systemd que tienes en los lb
    sidekiq_unit_pattern: "sidekiq-*.service"

    # Redis de producción (lo vi en el dashboard de Sidekiq)
    redis_host: "104.236.33.109"
    redis_port: 6379

  pre_tasks:
    - name: Comprobar que Redis responde antes de tocar Sidekiq
      ansible.builtin.wait_for:
        host: "{{ redis_host }}"
        port: "{{ redis_port }}"
        timeout: 10
      register: redis_ok

    - name: Fallar si Redis no responde
      ansible.builtin.fail:
        msg: "Redis {{ redis_host }}:{{ redis_port }} no responde; se evita reiniciar Sidekiq."
      when: not redis_ok.elapsed is defined

    - name: Descubrir units Sidekiq presentes en este host
      ansible.builtin.shell: |
        set -o pipefail
        systemctl list-units --type=service "{{ sidekiq_unit_pattern }}" \
          --all --no-legend --no-pager | awk '{print $1}'
      args:
        executable: /bin/bash
      changed_when: false
      register: sidekiq_units_raw

    - name: Normalizar lista de units
      ansible.builtin.set_fact:
        sidekiq_units: "{{ sidekiq_units_raw.stdout_lines | select('match', '.*\\.service$') | list }}"

    - name: Asegurar que hay al menos una unit sidekiq en este host
      ansible.builtin.fail:
        msg: "No se encontraron units que coincidan con {{ sidekiq_unit_pattern }} en {{ inventory_hostname }}."
      when: sidekiq_units | length == 0

  tasks:
    - name: Reiniciar cada unit sidekiq encontrada
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
      loop: "{{ sidekiq_units }}"
      register: restart_results

    - name: Verificar que quedaron en estado 'active (running)'
      ansible.builtin.command: systemctl is-active "{{ item }}"
      changed_when: false
      loop: "{{ sidekiq_units }}"

    - name: Mostrar resumen por host (qué units se tocaron)
      ansible.builtin.debug:
        msg: "Reiniciadas en {{ inventory_hostname }}: {{ sidekiq_units | join(', ') }}"
