---
- name: Build transient group with selected droplets
  hosts: localhost
  gather_facts: no

  vars:
    selected_droplets: "{{ droplet_names | default([]) }}"
    slack_webhook_url: "{{ SLACK_WEBHOOK_URL | default('') }}"
    start_time: "{{ lookup('pipe', 'date +%s') }}"

    # 🔹 Mapa estático de nombres descriptivos a IPs (no depende del inventario)
    droplet_map:
      production-lb01: 165.227.210.87
      production-lb02: 159.203.94.161
      production-lb03: 134.209.34.218
      production-lb04: 134.209.34.40
      load-balancer: 167.99.60.242
      db-replication: 104.236.149.105
      production-db: 104.236.33.109
      contract: 107.170.0.247
      postgres-etf: 134.209.124.111
      restful-api: 137.184.63.106
      erp-test-stage: 165.227.69.194
      sunlux: 45.55.36.150

  tasks:
    - name: Validate survey input
      assert:
        that: selected_droplets | length > 0
        fail_msg: "❌ You must select at least one droplet by name."
        success_msg: "✅ Selected droplets: {{ selected_droplets | join(', ') }}"

    - name: Resolve selected droplets using droplet_map
      set_fact:
        droplet_ips: "{{ droplet_ips | default({}) | combine({item: droplet_map[item]}) }}"
      loop: "{{ selected_droplets }}"
      when: droplet_map[item] is defined

    - name: Fail if any droplet is missing in map
      assert:
        that: droplet_ips | length == selected_droplets | length
        fail_msg: "❌ Some selected droplets are missing from droplet_map."
        success_msg: "✅ All selected droplets resolved to IPs."

    - name: Create transient group 'reboot_batch'
      add_host:
        name: "{{ item.key }}"
        ansible_host: "{{ item.value }}"
        groups: reboot_batch
      loop: "{{ droplet_ips | dict2items }}"

    - name: Notify global start on Slack
      when: slack_webhook_url | length > 0
      uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: "⚙️ Starting sequential reboot of *{{ selected_droplets | join(', ') }}* droplets..."
      changed_when: false
      ignore_errors: true
