---
- name: Restart selected DigitalOcean droplets (by name, sequentially)
  hosts: digital_ocean
  gather_facts: no
  serial: 1

  vars:
    selected_droplets: "{{ survey_droplets | default([]) }}"
    slack_webhook_url: "{{ SLACK_WEBHOOK_URL | default(omit) }}"
    restarted_ok: []
    restarted_fail: []
    start_time: "{{ lookup('pipe', 'date +%s') | int }}"

  pre_tasks:
    - name: Validate survey input
      ansible.builtin.assert:
        that:
          - selected_droplets | length > 0
        fail_msg: "❌ Please select at least one droplet to reboot."
        success_msg: "✅ Selected droplets: {{ selected_droplets | join(', ') }}"
      run_once: true
      delegate_to: localhost

    - name: Notify global start on Slack
      ansible.builtin.uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: "⚙️ Starting reboot process for: {{ selected_droplets | join(', ') }}"
      run_once: true
      delegate_to: localhost
      when: slack_webhook_url is defined
      ignore_errors: true

  tasks:
    - name: Skip hosts not selected
      ansible.builtin.meta: end_host
      when: inventory_hostname not in selected_droplets

    - name: Process each selected droplet
      block:
        - name: Announce reboot start for host
          ansible.builtin.uri:
            url: "{{ slack_webhook_url }}"
            method: POST
            headers:
              Content-Type: "application/json"
            body_format: json
            body:
              text: "🔄 Rebooting *{{ inventory_hostname }}* ({{ ansible_host }})..."
          delegate_to: localhost
          when: slack_webhook_url is defined
          ignore_errors: true

        - name: Reboot droplet
          become: true
          ansible.builtin.reboot:
            post_reboot_delay: 10
            reboot_timeout: 900
            test_command: "whoami"

        - name: Register success
          ansible.builtin.set_fact:
            restarted_ok: "{{ restarted_ok + [inventory_hostname] }}"
          delegate_to: localhost

        - name: Notify success on Slack
          ansible.builtin.uri:
            url: "{{ slack_webhook_url }}"
            method: POST
            headers:
              Content-Type: "application/json"
            body_format: json
            body:
              text: "✅ *{{ inventory_hostname }}* reboot completed successfully."
          delegate_to: localhost
          when: slack_webhook_url is defined
          ignore_errors: true

        - name: Pause 30 seconds before next droplet
          ansible.builtin.pause:
            seconds: 30

      rescue:
        - name: Register failure
          ansible.builtin.set_fact:
            restarted_fail: "{{ restarted_fail + [inventory_hostname] }}"
          delegate_to: localhost

        - name: Notify failure on Slack
          ansible.builtin.uri:
            url: "{{ slack_webhook_url }}"
            method: POST
            headers:
              Content-Type: "application/json"
            body_format: json
            body:
              text: "❗ Reboot failed for *{{ inventory_hostname }}* ({{ ansible_host }})"
          delegate_to: localhost
          when: slack_webhook_url is defined
          ignore_errors: true

      always:
        - name: Ensure continuation to next droplet
          debug:
            msg: "Continuing to next droplet..."

  post_tasks:
    - name: Calculate total duration
      ansible.builtin.set_fact:
        total_duration: "{{ (lookup('pipe', 'date +%s') | int - start_time) | int }}"
        minutes: "{{ (total_duration // 60) | int }}"
        seconds: "{{ (total_duration % 60) | int }}"
      run_once: true
      delegate_to: localhost

    - name: Send final Slack summary
      ansible.builtin.uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: >-
            {% if (restarted_fail | length | int) == 0 %}
            ✅ *Reboot Summary (All Successful)*:
            {% else %}
            ⚠️ *Reboot Summary (Partial Failures)*:
            {% endif %}
            - Successful: {{ restarted_ok | unique | join(', ') | default('none') }}
            {% if (restarted_fail | default([])) | length > 0 %}
            - Failed: {{ restarted_fail | unique | join(', ') }}
            {% endif %}
            - ⏱️ Completed in {{ minutes }}m {{ seconds }}s.
            - Total servers processed: {{ (restarted_ok | length + restarted_fail | length) }}
      run_once: true
      delegate_to: localhost
      when: slack_webhook_url is defined
      ignore_errors: true
