---
- name: Restart selected Rails apps (Passenger) by touching restart.txt
  hosts: app_servers
  become: yes
  gather_facts: no

  vars:
    app_root: /home/deploy
    app_prefix: erp

    # Nombre EXACTO que debes usar en el Survey (Multiple Choice - multiple)
    # Ej.: accltd, bzidat, espdat, mxpdat, pwcdat, rdmdat, saldat, covdat, prndat, wepdat
    apps_selected: "{{ apps_selected | default([]) }}"

    # Normaliza por si alguien incluye el prefijo "erp-"
    apps: "{{ apps_selected | map('regex_replace', '^erp-', '') | list }}"

  pre_tasks:
    - name: Validate survey selection
      assert:
        that:
          - apps_selected is sequence
          - apps_selected | length > 0
        fail_msg: "Survey must provide at least one company in 'apps_selected'."

    - name: Show target host and chosen apps
      debug:
        msg: "Host {{ inventory_hostname }} → will restart: {{ apps | join(', ') }}"

  tasks:
    - name: Ensure Passenger tmp dir exists (per app)
      file:
        path: "{{ app_root }}/{{ app_prefix }}-{{ item }}/current/tmp"
        state: directory
        owner: deploy
        group: deploy
        mode: "0775"
      loop: "{{ apps }}"
      loop_control:
        label: "{{ app_prefix }}-{{ item }}"
      tags: [ensure_tmp]

    - name: Touch restart.txt (Passenger rolling restart)
      become_user: deploy
      file:
        path: "{{ app_root }}/{{ app_prefix }}-{{ item }}/current/tmp/restart.txt"
        state: touch
        modification_time: preserve
        access_time: preserve
      loop: "{{ apps }}"
      loop_control:
        label: "{{ app_prefix }}-{{ item }}"
      register: passenger_touch
      tags: [restart]

    - name: Report what was restarted on this host
      debug:
        msg: >
          Passenger restart triggered for apps: {{
            passenger_touch.results
            | map(attribute='item')
            | map('regex_replace', '^', app_prefix ~ '-')
            | join(', ')
          }}

    - name: Wait a short grace period
      wait_for:
        timeout: 5
      tags: [wait]
