---
- name: Resolve droplet IP from inventory
  set_fact:
    droplet_ip: "{{ hostvars[droplet_name].ansible_host | default('unknown') }}"
  when: hostvars[droplet_name] is defined

- name: Announce reboot start for droplet
  ansible.builtin.uri:
    url: "{{ slack_webhook_url }}"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      text: >-
        🔄 *Step {{ droplet_index + 1 }}/{{ selected_droplets | length }}:* Rebooting *{{ droplet_name }}*
        ({{ droplet_ip }})...
  when: slack_webhook_url is defined
  ignore_errors: true

- name: Reboot droplet using Ansible connection
  delegate_to: "{{ droplet_ip }}"
  become: yes
  become_user: root
  ansible.builtin.reboot:
    reboot_timeout: 180
    test_command: uptime
  register: reboot_result
  ignore_errors: true

- name: Pause 30 seconds before next
  ansible.builtin.pause:
    seconds: 30

- name: Record success or failure
  set_fact:
    restarted_ok: "{{ restarted_ok + [droplet_name] if reboot_result.rc == 0 else restarted_ok }}"
    restarted_fail: "{{ restarted_fail + [droplet_name] if reboot_result.rc != 0 else restarted_fail }}"

- name: Notify per-droplet result on Slack
  ansible.builtin.uri:
    url: "{{ slack_webhook_url }}"
    method: POST
    headers:
      Content-Type: "application/json"
    body_format: json
    body: >-
      {% if reboot_result.rc == 0 %}
      ✅ *{{ droplet_name }}* rebooted successfully ({{ droplet_ip }}).
      {% else %}
      ❌ Failed to reboot *{{ droplet_name }}* ({{ droplet_ip }}).
      {% endif %}
  when: slack_webhook_url is defined
  ignore_errors: true
