---
- name: Reiniciar una VM de Proxmox usando comandos qm y Credencial SSH
  # Ejecutamos en el nodo PVE donde se encuentra la VM, NO en el AWX (localhost)
  hosts: '{{ vm_to_restart | lower }}_host'
  connection: ssh
  become: yes # Asegura que se use el usuario root
  gather_facts: no

  vars:
    # Obtener el ID de la VM
    vm_vmid: "{{ hostvars[inventory_hostname]['proxmox_vms'][vm_to_restart | lower]['vmid'] }}"
    # Obtener el OS de la VM para la lógica de retardo
    vm_os: "{{ hostvars[inventory_hostname]['proxmox_vms'][vm_to_restart | lower]['os'] | lower }}"

  tasks:
    - name: Determinar el Host Proxmox y la VM
      debug:
        msg: "Conectándose al host: {{ inventory_hostname }}. Reiniciando VM (ID: {{ vm_vmid }})"
      run_once: yes

    - name: Reiniciar la VM usando 'qm reboot'
      ansible.builtin.command: "qm reboot {{ vm_vmid }}"
      # Nota: qm reboot intenta un apagado elegante, si falla usa el parámetro '--force'

    - name: Esperar 2 minutos (120 segundos) después del reinicio de Windows
      ansible.builtin.wait_for:
        timeout: 120
      when: vm_os == 'windows'
