# Archivo: restart_single_vm.yml
---
- name: "1. Confirmar destino (VM: {{ vm_name | upper }}, Nodo: {{ vm_pve_node_name }})"
  ansible.builtin.debug:
    msg: "Reiniciando {{ vm_name }} (ID: {{ vm_vmid }}) en el nodo PVE: {{ vm_pve_node_name }} ({{ pve_host_ip }})"

- name: "2. Reiniciar la VM {{ vm_name | upper }} usando 'qm reboot'"
  ansible.builtin.command: "qm reboot {{ vm_vmid }}"
  delegate_to: "{{ pve_host_ip }}"
  vars:
    # Autenticación por Llave SSH configurada en la Credencial de AWX
    ansible_user: root 
    
- name: "3. Esperar 2 minutos para Windows (VM: {{ vm_name | upper }})"
  ansible.builtin.wait_for:
    timeout: 60
  when: vm_os == 'windows'
