# Archivo: restart_single_vm.yml
---
# ... (Tareas 1a y 1b eliminadas, ya que no son necesarias si las variables se pasan correctamente) ...

- name: "1. Confirmar destino (VM: {{ vm_name | upper }}, Nodo: {{ vm_pve_node_name }})"
  ansible.builtin.debug:
    msg: "Reiniciando {{ vm_name }} (ID: {{ vm_vmid }}) en el nodo PVE: {{ vm_pve_node_name }} ({{ pve_host_ip }})"

- name: "2. Reiniciar la VM {{ vm_name | upper }} usando 'qm reboot'"
  ansible.builtin.command: "qm reboot {{ vm_vmid }}"
  delegate_to: "{{ pve_host_ip }}"
  vars:
    # Pasamos el usuario y la contraseña explícitamente para la conexión delegada.
    ansible_user: root
    ansible_password: "{{ root_password }}"  # Variable del Custom Credential de AWX
    
- name: "3. Esperar 2 minutos para Windows (VM: {{ vm_name | upper }})"
  ansible.builtin.wait_for:
    timeout: 120
  when: vm_os == 'windows'
