---
- name: Reiniciar una VM de Proxmox usando comandos qm a través de SSH
  # El play se ejecuta en el servidor AWX (localhost)
  hosts: localhost
  gather_facts: no

  vars:
    # Las variables de datos (vms_data, pve_nodes) se inyectan desde el Job Template (Extra Variables).
    
    # --- DATOS DE LA VM SELECCIONADA ---
    vm_details: "{{ vms_data[vm_to_restart | lower] }}"
    vm_vmid: "{{ vm_details.vmid }}"
    vm_pve_node_name: "{{ vm_details.pve_node | lower }}"
    vm_os: "{{ vm_details.os | lower }}"

    # --- DETALLE DE CONEXIÓN ---
    # Obtenemos la IP real del nodo PVE para el 'delegate_to'
    pve_host_ip: "{{ pve_nodes[vm_pve_node_name] }}"
    
  tasks:
    - name: 1. Confirmar la VM y el nodo de destino
      debug:
        msg: "VM: {{ vm_to_restart }} (ID: {{ vm_vmid }}). Delegando comando SSH al nodo PVE: {{ vm_pve_node_name }} ({{ pve_host_ip }})"
      run_once: true

    - name: 2. Reiniciar la VM usando 'qm reboot'
      ansible.builtin.command: "qm reboot {{ vm_vmid }}"
      # DELEGACIÓN CLAVE: Ejecuta el comando en la IP específica del nodo PVE.
      delegate_to: "{{ pve_host_ip }}"
      vars:
        # La Credencial Machine debe ser la del usuario 'administrator'.
        ansible_user: administrator 
        
    - name: 3. Esperar 2 minutos (120 segundos) después del reinicio de Windows
      ansible.builtin.wait_for:
        timeout: 120
      when: vm_os == 'windows'
