---
- name: Reiniciar VMs seleccionadas usando SSH y Delegación
  hosts: localhost
  gather_facts: no
  
  vars:
    # Carga de Variables (CRÍTICA)
    pve_group_vars: "{{ hostvars['pve20'] }}"
    vms_data: "{{ pve_group_vars.proxmox_vms }}"
    pve_nodes: "{{ pve_group_vars.pve_nodes }}"
    
  tasks:
    - name: Iterar sobre la lista de VMs seleccionadas
      ansible.builtin.include_tasks: restart_single_vm.yml
      loop: "{{ vm_to_restart }}"
      loop_control:
        loop_var: current_vm_name
      
      # Variables pasadas al archivo incluido:
      vars:
        vm_name: "{{ current_vm_name | lower }}"
        vm_details: "{{ vms_data[current_vm_name | lower] }}"
        vm_vmid: "{{ vm_details.vmid }}"
        vm_pve_node_name: "{{ vm_details.pve_node | lower }}"
        vm_os: "{{ vm_details.os | lower }}"
        pve_host_ip: "{{ pve_nodes[vm_details.pve_node | lower] }}"
