---
- name: Upload JSON analysis files for all companies to AWS S3
  hosts: all
  become: yes
  gather_facts: no

  vars:
    region: "us-east-1"
    json_path: "/home/deploy/{{ item }}/current/public/json/"
    key_prefix: "json"
    permission: "public-read"

    # Lista de compañías a sincronizar
    companies:
      - erp-accltd
      - erp-bzidat
      - erp-espdat
      - erp-mxpdat
      - erp-pwcdat
      - erp-rdmdat
      - erp-saldat
      - erp-covdat
      - erp-prndat
      - erp-wepdat

  tasks:

    - name: Upload JSON files to AWS S3 for each company
      amazon.aws.s3_sync:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        bucket: "{{ bucket }}"
        region: "{{ region }}"
        file_root: "{{ json_path }}"
        key_prefix: "{{ key_prefix }}"
        permission: "{{ permission }}"
        include: "*.json"
      loop: "{{ companies }}"
      register: s3_results
      ignore_errors: true
      tags: sync

    - name: Display upload summary
      debug:
        msg: >
          Upload finished for {{ item.item }} → 
          changed={{ item.changed | default(false) }},
          failed={{ item.failed | default(false) }}
      loop: "{{ s3_results.results }}"
      tags: report

    - name: Send Slack notification on success
      community.general.slack:
        token: "{{ slack_token }}"
        msg: ":white_check_mark: JSON synchronization completed successfully for all companies."
        color: "good"
        channel: "#it-alerts"
      when: s3_results is defined and (s3_results.results | selectattr('failed','equalto',false) | list | length) > 0
      ignore_errors: true

    - name: Send Slack notification on failure
      community.general.slack:
        token: "{{ slack_token }}"
        msg: ":x: One or more JSON synchronizations failed. Please check the AWX job output."
        color: "danger"
        channel: "#it-alerts"
      when: s3_results is defined and (s3_results.results | selectattr('failed','equalto',true) | list | length) > 0
      ignore_errors: true
