---
- name: Sync all JSON reports to AWS S3 and notify via Slack
  hosts: all
  become: yes
  gather_facts: no

  vars:
    aws_region: "us-east-1"
    bucket: "erp-accpac"
    s3_prefix: "json"
    json_base_path: "/home/deploy"
    companies:
      - erp-accltd
      - erp-bzidat
      - erp-espdat
      - erp-mxpdat
      - erp-pwcdat
      - erp-rdmdat
      - erp-saldat
      - erp-covdat
      - erp-prndat
      - erp-wepdat

  pre_tasks:
    - name: Install boto3 (for AWS API access)
      ansible.builtin.pip:
        name:
          - boto3
          - botocore
      ignore_errors: yes

    - name: Install required Ansible collections (AWS + Slack)
      ansible.builtin.command: ansible-galaxy collection install amazon.aws community.general
      ignore_errors: yes

  tasks:
    - name: Upload JSON files for each company to S3
      amazon.aws.s3_sync:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        bucket: "{{ bucket }}"
        region: "{{ aws_region }}"
        file_root: "{{ json_base_path }}/{{ item }}/current/public/json"
        key_prefix: "{{ s3_prefix }}"
        permission: public-read
        include: "*.json"
      loop: "{{ companies }}"
      register: s3_result
      ignore_errors: yes

    - name: Check if any upload failed
      set_fact:
        upload_failed: "{{ s3_result.results | selectattr('failed','defined') | list | length > 0 }}"

    - name: Send Slack notification on success
      when: not upload_failed
      community.general.slack:
        token: "{{ slack_token }}"
        msg: "✅ Sales analysis JSON files successfully synchronized to AWS S3 bucket '{{ bucket }}'."
        color: good
        username: "AWX Bot"

    - name: Send Slack notification on failure
      when: upload_failed
      community.general.slack:
        token: "{{ slack_token }}"
        msg: "❌ Some JSON uploads failed during AWS S3 synchronization. Please check the AWX job logs."
        color: danger
        username: "AWX Bot"
