- hosts: all
  tasks:
  - name: Upload ACCPAC files
    s3_sync:
      aws_access_key: '{{aws_access_key}}'
      aws_secret_key: '{{aws_secret_key}}'
      bucket: 'vxaccpac'
      region: 'us-east-1'
      file_root: "/mnt/ACCPAC"
      key_prefix: "*"
      permission: public-read
      include: "*"
      exclude: "accpac*"
    ignore_errors: yes
    register: result

  - block:
    - name: Send notification message via Slack all options on FAILED
      slack:
        token: '{{slack_token}}'
        color: danger
        msg: 'VXACCPAC files synchronization failed with AWS S3 :-('
    when: result.failed == true

  - block:
    - name: Send notification message via Slack all options on SUCCESS
      slack:
        token: '{{slack_token}}'
        color: good
        msg: 'VXACCPAC files successfully synchronizing to AWS S3 :-)'
    when: result.failed == false