---
- hosts: all
  gather_facts: no
  vars:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    bucket: "{{ bucket }}"
    slack_token: "{{ slack_token }}"
    sync_failures: []
    
    companies:
      - erp-accltd
      - erp-bzidat
      - erp-espdat
      - erp-mxpdat
      - erp-pwcdat
      - erp-rdmdat
      - erp-saldat
      - erp-covdat
      - erp-prndat
      - erp-wepdat

  tasks:
    # 1. Tarea de sincronización: Módulo community.aws.s3_sync
    - name: 🔄 S3 Sync | Upload files for each site
      community.aws.s3_sync:
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{ aws_secret_key }}'
        bucket: '{{ bucket }}'
        region: 'us-east-1'
        file_root: "/home/deploy/{{ item }}/current/public/json/"
        key_prefix: "json/{{ item }}"
        permission: public-read
        include: "*"
      loop: "{{ companies }}" 
      ignore_errors: yes
      register: s3_results
    
    # 2. Registrar las compañías que fallaron
    - name: 📝 Log failed synchronizations
      set_fact:
        sync_failures: "{{ sync_failures + [item.item] }}"
      loop: "{{ s3_results.results }}"
      when: item.failed
    
    # 3. Notificación de Slack si hubo fallas
    - name: 🚨 Send FAILED notification for all failed sites via Slack
      community.general.slack:
        token: '{{ slack_token }}'
        color: danger
        msg: |
          🚨 Sales analysis synchronization **FAILED** on one or more sites (AWS S3).
          Failed sites: **{{ sync_failures | join(', ') }}**
      run_once: true
      when: sync_failures | length > 0

- hosts: localhost 
  tasks:
    # 4. Notificación final de éxito
    - name: ✅ Send SUCCESS/COMPLETION notification via Slack
      community.general.slack:
        token: '{{ slack_token }}'
        color: good
        msg: '✅ Sales analysis files successfully synchronized ({{ companies | length }} attempts) to AWS S3.'
