---
- name: Sync all JSON reports to AWS S3 and notify via Slack Webhook
  hosts: all
  become: yes
  vars:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    bucket: erp-accpac
    webhook_url: "{{ lookup('env', 'SLACK_WEBHOOK_URL') }}"
    companies:
      - erp-accltd
      - erp-bzidat
      - erp-espdat
      - erp-mxpdat
      - erp-pwcdat
      - erp-rdmdat
      - erp-saldat
      - erp-covdat
      - erp-prndat

  tasks:
    - name: Upload JSON files to S3 using AWS CLI for each company
      shell: >
        aws s3 sync /home/deploy/{{ item }}/current/public/json
        s3://{{ bucket }}/json/{{ item }}/
        --region us-east-1
        --acl public-read
        --delete
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
      register: upload_result
      loop: "{{ companies }}"
      ignore_errors: true

    - name: Determine overall upload result
      set_fact:
        upload_failed: "{{ upload_result is failed or upload_result.results | selectattr('rc', 'ne', 0) | list | length > 0 }}"

    - name: Prepare message for Slack
      set_fact:
        slack_message: >
          {% if not upload_failed %}
          ✅ *Sales JSON synchronization successful!* 🚀
          All JSON files uploaded correctly to S3 bucket *{{ bucket }}*.
          {% else %}
          ⚠️ *Sales JSON synchronization failed!* 😟
          Some companies had upload errors to S3 bucket *{{ bucket }}*.
          {% endif %}

    - name: Send notification to Slack via webhook
      ansible.builtin.uri:
        url: "{{ webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: "{{ slack_message }}"
      register: slack_webhook
      ignore_errors: true

    - name: Show Slack response
      debug:
        var: slack_webhook
