---
- name: Upload all company JSON analysis files to AWS S3
  hosts: all
  become: yes
  gather_facts: no
  serial: 1

  vars:
    region: "us-east-1"
    json_root: "/home/deploy"
    companies:
      - erp-accltd
      - erp-bzidat
      - erp-espdat
      - erp-mxpdat
      - erp-pwcdat
      - erp-rdmdat
      - erp-saldat
      - erp-covdat
      - erp-prndat
      - erp-wepdat

  tasks:

    - name: Find JSON files for each company
      ansible.builtin.find:
        paths: "{{ json_root }}/{{ item }}/current/public/json/"
        patterns: "*.json"
      loop: "{{ companies }}"
      register: found_files

    - name: Upload JSON files to AWS S3
      aws_s3:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        bucket: "{{ bucket }}"
        region: "{{ region }}"
        mode: put
        permission: public-read
        src: "{{ file_item.path }}"
        object: "json/{{ item.item }}/{{ file_item.path | basename }}"
      loop: "{{ found_files.results | subelements('files') }}"
      loop_control:
        label: "{{ file_item.path }}"
      ignore_errors: yes
      register: upload_result

    - name: Send Slack notification on failure
      when: upload_result.failed
      community.general.slack:
        token: "{{ slack_token }}"
        color: danger
        msg: ":x: JSON sync to AWS S3 failed for one or more companies."

    - name: Send Slack notification on success
      when: not upload_result.failed
      community.general.slack:
        token: "{{ slack_token }}"
        color: good
        msg: ":white_check_mark: JSON files successfully synchronized to AWS S3."
