---
- name: Sync all JSON reports to AWS S3 and notify via Slack (CLI + Debug)
  hosts: all
  become: yes
  vars:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    bucket: erp-accpac
    slack_token: "{{ lookup('env', 'SLACK_TOKEN') }}"
    slack_channel: "#vertilux"
    companies:
      - erp-accltd
      - erp-bzidat
      - erp-espdat
      - erp-mxpdat
      - erp-pwcdat
      - erp-rdmdat
      - erp-saldat
      - erp-covdat
      - erp-prndat

  tasks:
    - name: Upload JSON files to S3 using AWS CLI for each company
      shell: >
        aws s3 sync /home/deploy/{{ item }}/current/public/json
        s3://{{ bucket }}/json/{{ item }}/
        --region us-east-1
        --acl public-read
        --delete
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
      register: upload_result
      loop: "{{ companies }}"
      ignore_errors: true

    - name: Determine overall upload result
      set_fact:
        upload_failed: "{{ upload_result is failed or upload_result.results | selectattr('rc', 'ne', 0) | list | length > 0 }}"

    - name: Print summary of uploaded companies
      debug:
        msg: |
          ✅ Successful uploads:
          {{ upload_result.results | selectattr('rc', 'eq', 0) | map(attribute='item') | list | join(', ') }}
          ❌ Failed uploads:
          {{ upload_result.results | selectattr('rc', 'ne', 0) | map(attribute='item') | list | join(', ') }}

    - name: Send Slack notification (always)
      ansible.builtin.uri:
        url: "https://slack.com/api/chat.postMessage"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ slack_token }}"
        body_format: json
        body: >
          {{
            {
              "channel": slack_channel,
              "text": (
                "✅ *Sales JSON synchronization successful!* :rocket:\n"
                "All JSON files uploaded correctly to S3 bucket *" + bucket + "*."
                if not upload_failed else
                "⚠️ *Sales JSON synchronization failed!* :warning:\n"
                "Some companies did not upload successfully to S3 bucket *" + bucket + "*."
              )
            }
          }}
      register: slack_response
      ignore_errors: true

    - name: Show Slack response for verification
      debug:
        var: slack_response

    - name: Fail play if Slack API returned error
      when: slack_response.status | default(0) != 200 or (slack_response.json.ok | default(false)) == false
      fail:
        msg: "Slack API error: {{ slack_response.json.error | default('unknown error') }}"
