---
- hosts: all
  gather_facts: no
  vars:
    # Variables de seguridad que se esperan como 'Extra Variables' en AWX/Ansible Tower
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    bucket: "{{ bucket }}"
    slack_token: "{{ slack_token }}"
    
    # Lista fija de compañías (sites) a sincronizar
    companies:
      - erp-accltd
      - erp-bzidat
      - erp-espdat
      - erp-mxpdat
      - erp-pwcdat
      - erp-rdmdat
      - erp-saldat
      - erp-covdat
      - erp-prndat
      - erp-wepdat

  tasks:
    # Tarea principal que envuelve el loop.
    - name: LOOP | Synchronize sales analysis files for each company to AWS S3
      # El 'loop' se aplica directamente al bloque de tareas
      loop: "{{ companies }}"
      loop_control:
        loop_var: current_site
      
      # INICIO DEL BLOQUE DE TAREAS ITERATIVO
      block:
        - name: Upload files for site {{ current_site }}
          ansible.builtin.s3_sync:
            aws_access_key: '{{ aws_access_key }}'
            aws_secret_key: '{{ aws_secret_key }}'
            bucket: '{{ bucket }}'
            region: 'us-east-1'
            # Ruta de origen dinámica: /home/deploy/erp-accltd/current/public/json/
            file_root: "/home/deploy/{{ current_site }}/current/public/json/"
            # Prefijo S3 dinámico para organizar por compañía: json/erp-accltd
            key_prefix: "json/{{ current_site }}"
            permission: public-read
            include: "*"
          # Permite que la sincronización de una compañía falle sin detener todo el playbook
          ignore_errors: yes
          register: s3_result_{{ current_site }} # Registro dinámico para seguimiento

        # 2. Notificación de Slack solo si falla la sincronización de una compañía
        - name: Send FAILED notification for site {{ current_site }} via Slack
          community.general.slack:
            token: '{{ slack_token }}'
            color: danger
            msg: "🚨 Sales analysis synchronization **FAILED** for company **{{ current_site }}** (AWS S3)."
          # Se evalúa el registro dinámico específico de la compañía
          when: "hostvars[inventory_hostname]['s3_result_' + current_site ].failed"

# SEGUNDO PLAY: Notificación final (se ejecuta si el primer play no tuvo errores fatales)

- hosts: localhost # Ejecutar la notificación final localmente desde AWX/Tower
  tasks:
    - name: Send SUCCESS/COMPLETION notification via Slack
      community.general.slack:
        token: '{{ slack_token }}'
        color: good
        msg: '✅ Sales analysis files successfully synchronized for **all companies** to AWS S3.'
