---
- hosts: all
  gather_facts: no
  vars:
    # Variables de seguridad que se esperan como 'Extra Variables' en AWX/Ansible Tower
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    bucket: "{{ bucket }}"
    slack_token: "{{ slack_token }}"
    
    # Lista fija de compañías (sites) a sincronizar
    companies:
      - erp-accltd
      - erp-bzidat
      - erp-espdat
      - erp-mxpdat
      - erp-pwcdat
      - erp-rdmdat
      - erp-saldat
      - erp-covdat
      - erp-prndat
      - erp-wepdat

  tasks:
    # 1. Tarea principal: El LOOP ENVUELVE EL BLOQUE
    # (El 'loop' y el 'block' NO van en el mismo nivel horizontal)
    - name: LOOP | Synchronize sales analysis files for each company to AWS S3
      # El 'loop' se aplica directamente a la tarea
      loop: "{{ companies }}"
      loop_control:
        loop_var: current_site
      
      # El 'block' se INDENTA y contiene las tareas que se repiten
      block:
        - name: Upload files for site {{ current_site }}
          ansible.builtin.s3_sync:
            aws_access_key: '{{ aws_access_key }}'
            aws_secret_key: '{{ aws_secret_key }}'
            bucket: '{{ bucket }}'
            region: 'us-east-1'
            file_root: "/home/deploy/{{ current_site }}/current/public/json/"
            key_prefix: "json/{{ current_site }}"
            permission: public-read
            include: "*"
          ignore_errors: yes
          # Se registra el resultado en una variable única por sitio
          register: s3_result_{{ current_site }} 

        # 2. Notificación de Slack solo si falla la sincronización
        - name: Send FAILED notification for site {{ current_site }} via Slack
          community.general.slack:
            token: '{{ slack_token }}'
            color: danger
            msg: "🚨 FAILED sync for **{{ current_site }}**."
          # Se evalúa el registro dinámico
          when: "hostvars[inventory_hostname]['s3_result_' + current_site ].failed"
          # La tarea se ejecuta, pero la notificación solo se envía si falla la condición 'when'

# SEGUNDO PLAY: Notificación final de éxito
- hosts: localhost 
  tasks:
    - name: Send SUCCESS/COMPLETION notification via Slack
      community.general.slack:
        token: '{{ slack_token }}'
        color: good
        msg: '✅ Sales analysis files successfully synchronized for **all companies** to AWS S3.'
