---
- name: Sync all JSON reports to AWS S3 and notify via Slack Webhook
  hosts: all
  become: yes
  vars:
    bucket: erp-accpac
    slack_webhook_url: "{{ SLACK_WEBHOOK_URL }}"

    companies:
      - erp-accltd
      - erp-bzidat
      - erp-espdat
      - erp-mxpdat
      - erp-pwcdat
      - erp-rdmdat
      - erp-saldat
      - erp-covdat
      - erp-prndat

  tasks:

    - name: Verify AWS credentials availability
      assert:
        that:
          - lookup('env', 'AWS_ACCESS_KEY_ID') | length > 0
          - lookup('env', 'AWS_SECRET_ACCESS_KEY') | length > 0
        fail_msg: "AWS credentials are missing. Make sure the AWS credential is attached to this template."
        success_msg: "AWS credentials detected and available."

    - name: Upload JSON files to S3 using AWS CLI for each company
      shell: >
        aws s3 sync /home/deploy/{{ item }}/current/public/json
        s3://{{ bucket }}/json/{{ item }}/
        --region us-east-1
        --acl public-read
        --delete
      register: upload_result
      loop: "{{ companies }}"
      ignore_errors: true

    - name: Determine overall upload result
      set_fact:
        upload_failed: "{{ upload_result is failed or upload_result.results | selectattr('rc', 'ne', 0) | list | length > 0 }}"

    - name: Build Slack message
      set_fact:
        slack_message: >
          {% if not upload_failed %}
          ✅ *Sales analysis files synchronization to AWS*
              accltd    bzidat   espdat   mxpdat   pwcdat
              rdmdat   saldat   covdat   prndat
          All JSON files uploaded successfully to S3 bucket *{{ bucket }}*.
          {% else %}
          ⚠️ *Sales JSON synchronization failed!* 😟
          Some companies had upload errors in bucket *{{ bucket }}*.
          {% endif %}

    - name: Send notification to Slack via webhook
      ansible.builtin.uri:
        url: "{{ slack_webhook_url }}"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          text: "{{ slack_message }}"
      when: slack_webhook_url is defined
      register: slack_response
      ignore_errors: true

    - name: Show Slack response
      debug:
        var: slack_response
      when: slack_response is defined
