---
- name: Network Control for Selected VMs
  hosts: localhost
  gather_facts: no
  
  vars:
    # Critical Variables: Ensures group variables are loaded.
    pve_group_vars: "{{ hostvars['pve20'] }}"
    vms_data: "{{ pve_group_vars.proxmox_vms }}"
    pve_nodes: "{{ pve_group_vars.pve_nodes }}"
    
  tasks:
    - name: Validate if a correct network action was selected
      ansible.builtin.fail:
        msg: "You must select a valid action mode: net_off (disconnect) or net_on (connect)."
      when: net_action not in ['net_off', 'net_on']

    - name: Iterate over selected VMs and include network logic
      ansible.builtin.include_tasks: vm_net_logic.yml
      # 'vm_to_restart' is the list from the Survey
      loop: "{{ vm_to_restart }}"
      loop_control:
        loop_var: current_vm_name
      
      # Variables passed to the included file
      vars:
        vm_name: "{{ current_vm_name | lower }}"
        vm_details: "{{ vms_data[current_vm_name | lower] }}"
        vm_vmid: "{{ vm_details.vmid }}"
        vm_pve_node_name: "{{ vm_details.pve_node | lower }}"
        vm_os: "{{ vm_details.os | lower }}"
        pve_host_ip: "{{ pve_nodes[vm_details.pve_node | lower] }}"
