---
- name: Control de Red de VMs seleccionadas
  hosts: localhost
  gather_facts: no
  
  vars:
    # Carga de Variables
    pve_group_vars: "{{ hostvars['pve20'] }}"
    vms_data: "{{ pve_group_vars.proxmox_vms }}"
    pve_nodes: "{{ pve_group_vars.pve_nodes }}"
    
  tasks:
    - name: Verificar si se seleccionó una acción de red válida
      ansible.builtin.fail:
        msg: "Debe seleccionar un modo de acción válido: net_off (desconectar) o net_on (conectar)."
      when: net_action not in ['net_off', 'net_on']

    - name: Iterar sobre las VMs seleccionadas e incluir la lógica de red
      ansible.builtin.include_tasks: vm_net_logic.yml
      # La lista de VMs es 'vm_to_restart'
      loop: "{{ vm_to_restart }}"
      loop_control:
        loop_var: current_vm_name
      
      # Variables de la iteración pasadas al archivo incluido
      vars:
        vm_name: "{{ current_vm_name | lower }}"
        vm_details: "{{ vms_data[current_vm_name | lower] }}"
        vm_vmid: "{{ vm_details.vmid }}"
        vm_pve_node_name: "{{ vm_details.pve_node | lower }}"
        vm_os: "{{ vm_details.os | lower }}"
        pve_host_ip: "{{ pve_nodes[vm_details.pve_node | lower] }}"
