---
- name: Graceful VM Shutdown by Node
  hosts: localhost
  gather_facts: no
  
  # Asumiendo que las variables de tu inventario se cargan a través de hostvars
  vars:
    pve_group_vars: "{{ hostvars['pve20'] }}" 
    vms_data: "{{ pve_group_vars.proxmox_vms }}"
    pve_nodes: "{{ pve_group_vars.pve_nodes }}"

  tasks:
    - name: Iterate over selected nodes and execute shutdown logic
      ansible.builtin.include_tasks: shutdown_node_logic.yml
      # 'target_pve_nodes' es la lista del Survey (e.g., ['pve50', 'pve70'])
      loop: "{{ target_pve_nodes }}"
      loop_control:
        loop_var: current_node_name
