---
- name: Apagado Grácil de VMs por Nodo
  hosts: localhost
  gather_facts: no
  
  # Asumiendo que las variables de tu inventario se cargan a través de hostvars
  vars:
    pve_group_vars: "{{ hostvars['pve20'] }}" 
    vms_data: "{{ pve_group_vars.proxmox_vms }}"
    pve_nodes: "{{ pve_group_vars.pve_nodes }}"

  tasks:
    - name: Iterar sobre los nodos seleccionados y ejecutar el apagado
      ansible.builtin.include_tasks: shutdown_node_logic.yml
      # La variable 'target_pve_nodes' es la lista del Survey (['pve50', 'pve70', ...])
      loop: "{{ target_pve_nodes }}"
      loop_control:
        loop_var: current_node_name
