# Archivo: vm_net_logic.yml
---
# Tarea 1a: Obtener la configuración de red de la VM usando 'qm config'
- name: "1a. Obtener la línea de configuración de net0"
  ansible.builtin.shell: "qm config {{ vm_vmid }} | grep net0"
  delegate_to: "{{ pve_host_ip }}"
  vars:
    ansible_user: root
  register: qm_config_output
  
- name: "1b. Extraer, limpiar y determinar el estado actual"
  ansible.builtin.set_fact:
    net0_config_full: "{{ qm_config_output.stdout | regex_replace('^net0: ', '') | trim }}"
    # Determina si está apagada (link_down=1) o encendida (ausente/link_down=0)
    is_currently_down: "{{ 'link_down=1' in qm_config_output.stdout }}"
    # Crea la configuración limpia (sin link_down) para encender
    net0_config_clean: "{{ qm_config_output.stdout | regex_replace('^net0: ', '') | regex_replace(',link_down=[01]', '') | trim }}"

# ----------------------------------------------------
# A. LÓGICA NET_OFF (Apagar)
# ----------------------------------------------------
- name: "2a. [NET_OFF] Desconectar la tarjeta de red (Apagar)"
  ansible.builtin.command: "qm set {{ vm_vmid }} --net0 {{ net0_config_clean }},link_down=1"
  delegate_to: "{{ pve_host_ip }}"
  vars:
    ansible_user: root 
  when: 
    - net_action == 'net_off'
    - not is_currently_down # Solo actuar si actualmente está ENCENDIDA (no down)
  register: net_action_result

- name: "2b. [NET_OFF] Notificar: Ya estaba apagada"
  ansible.builtin.debug:
    msg: " La red de {{ vm_name | upper }} ya estaba APAGADA (link_down=1). No se realizó ningún cambio."
  when: 
    - net_action == 'net_off'
    - is_currently_down # Notificar si ya estaba APAGADA

# ----------------------------------------------------
# B. LÓGICA NET_ON (Encender)
# ----------------------------------------------------
- name: "3a. [NET_ON] Conectar la tarjeta de red (Encender)"
  ansible.builtin.command: "qm set {{ vm_vmid }} --net0 {{ net0_config_clean }}"
  delegate_to: "{{ pve_host_ip }}"
  vars:
    ansible_user: root 
  when: 
    - net_action == 'net_on'
    - is_currently_down # Solo actuar si actualmente está APAGADA (down)
  register: net_action_result

- name: "3b. [NET_ON] Notificar: Ya estaba encendida"
  ansible.builtin.debug:
    msg: " La red de {{ vm_name | upper }} ya estaba ENCENDIDA (link_down=0 o ausente). No se realizó ningún cambio."
  when: 
    - net_action == 'net_on'
    - not is_currently_down # Notificar si ya estaba ENCENDIDA

# ----------------------------------------------------
# C. Notificación de Éxito (Si se realizó una acción)
# ----------------------------------------------------
- name: "4. Notificar acción completada"
  ansible.builtin.debug:
    msg: " La red de {{ vm_name | upper }} ha sido {% if net_action == 'net_off' %}APAGADA{% else %}ENCENDIDA{% endif %} con éxito."
  when: 
    - net_action_result is defined 
    - net_action_result.changed # Solo notificar si la tarea 2a o 3a cambió algo
