# Archivo: vm_net_logic.yml
---
- name: "1. Confirmar destino (VM: {{ vm_name | upper }}, Modo: {{ net_action | upper }})"
  ansible.builtin.debug:
    msg: "Ejecutando {{ net_action }} en {{ vm_name }} (ID: {{ vm_vmid }}) en nodo PVE: {{ pve_host_ip }}"

# --- ACCIÓN NET_OFF (Desconectar/Disable) ---
- name: "2a. [NET_OFF] Deshabilitar/Desconectar la tarjeta de red (net0) de {{ vm_name | upper }}"
  # CORRECCIÓN FINAL: Reaplicamos la configuración de net0, añadiendo 'disable=1'.
  # Usamos la sintaxis qm set <vmid> --<propiedad> <valor> para el dispositivo.
  # Proxmox requiere que el valor contenga todos los parámetros de la interfaz.
  # Eliminamos la opción que falló: '--net0.disable 1'
  # Y usamos la sintaxis completa:
  ansible.builtin.command: "qm set {{ vm_vmid }} --net0 model=virtio,bridge=vmbr0,disable=1"
  delegate_to: "{{ pve_host_ip }}"
  vars:
    ansible_user: root 
  when: net_action == 'net_off'

# --- ACCIÓN NET_ON (Conectar/Enable) ---
- name: "2b. [NET_ON] Habilitar/Conectar la tarjeta de red (net0) de {{ vm_name | upper }}"
  # CORRECCIÓN FINAL: Reaplicamos la configuración completa sin el parámetro 'disable=1'.
  ansible.builtin.command: "qm set {{ vm_vmid }} --net0 model=virtio,bridge=vmbr0"
  delegate_to: "{{ pve_host_ip }}"
  vars:
    ansible_user: root 
  when: net_action == 'net_on'
