# Archivo: vm_net_logic.yml
---
- name: "1. Confirmar destino (VM: {{ vm_name | upper }}, Modo: {{ net_action | upper }})"
  ansible.builtin.debug:
    msg: "Ejecutando {{ net_action }} en {{ vm_name }} (ID: {{ vm_vmid }}) en nodo PVE: {{ pve_host_ip }}"

# --- ACCIÓN NET_OFF (Desconectar/Disable) ---
- name: "2a. [NET_OFF] Deshabilitar/Desconectar la tarjeta de red (net0) de {{ vm_name | upper }}"
  # CORRECCIÓN: Usamos 'disable=1'. Solo modificamos el estado sin tocar bridge o model.
  ansible.builtin.command: "qm set {{ vm_vmid }} --net0 model=virtio,bridge=vmbr0,disable=1"
  delegate_to: "{{ pve_host_ip }}"
  vars:
    ansible_user: root 
  when: net_action == 'net_off'

# --- ACCIÓN NET_ON (Conectar/Enable) ---
- name: "2b. [NET_ON] Habilitar/Conectar la tarjeta de red (net0) de {{ vm_name | upper }}"
  # CORRECCIÓN: Borramos el parámetro 'disable' de la configuración de net0.
  # El parámetro 'delete' es necesario para eliminar una propiedad específica de la interfaz.
  ansible.builtin.command: "qm set {{ vm_vmid }} --delete net0.disable"
  delegate_to: "{{ pve_host_ip }}"
  vars:
    ansible_user: root 
  when: net_action == 'net_on'
