# Archivo: vm_net_logic.yml
---
# --- Tarea 1a: Obtener la configuración de red de la VM usando 'qm config' ---
- name: "1a. Obtener la línea de configuración de net0"
  # CORRECCIÓN: Usamos 'shell' para permitir la tubería '|' y 'grep'.
  ansible.builtin.shell: "qm config {{ vm_vmid }} | grep net0"
  delegate_to: "{{ pve_host_ip }}"
  vars:
    ansible_user: root
  register: qm_config_output
  
# --- Tarea 1b: Procesar y limpiar la configuración ---
- name: "1b. Extraer y limpiar la configuración de net0"
  ansible.builtin.set_fact:
    # Quitamos 'net0: ' del inicio y cualquier espacio en blanco al final.
    net0_config_full: "{{ qm_config_output.stdout | regex_replace('^net0: ', '') | trim }}"

- name: "2. Confirmar destino (VM: {{ vm_name | upper }}, Modo: {{ net_action | upper }})"
# ... (El resto del playbook se mantiene)
